// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-BVEKHBQ5.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-2HMR454I.js";
import { className, css, fonts } from "./chunks/chunk-URGOVI2W.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:accordion
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ajeCF25099Tfl6XN7DwZ/f9HGHMLVWTDraRDOZpz0/WNv4NxpCj.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	getFonts as getFonts2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/h8ioHyt4BUxuvVCE1Q10/aTM6mEMGlM19JjX8exDe/AvoidLayoutJumping_Prod.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useRef } from "react";
function AvoidLayoutJumping({ direction, style }) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const ref = useRef(null);
	const rafId = useRef();
	const vertical = direction === "vertical" || direction === "both";
	const horizontal = direction === "horizontal" || direction === "both";
	useEffect(() => {
		if (isCanvas) return;
		const parent = ref.current?.parentElement?.parentElement;
		if (!parent) return;
		const container = parent.parentElement;
		if (!container) return;
		const updateSize = () => {
			const rect = parent.getBoundingClientRect();
			if (horizontal) {
				container.style.width = `${rect.width}px`;
			}
			if (vertical) {
				container.style.height = `${rect.height}px`;
			}
			rafId.current = requestAnimationFrame(updateSize);
		};
		rafId.current = requestAnimationFrame(updateSize);
		return () => {
			if (rafId.current) {
				cancelAnimationFrame(rafId.current);
			}
			if (container) {
				if (horizontal) {
					container.style.width = "";
				}
				if (vertical) {
					container.style.height = "";
				}
			}
		};
	}, [direction]);
	return (
		<div
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
}
AvoidLayoutJumping.displayName = "Layout Jump Preventer";
addPropertyControls(AvoidLayoutJumping, {
	direction: {
		type: ControlType.Enum,
		defaultValue: "vertical",
		options: ["vertical", "horizontal", "both"],
		optionTitles: ["Vertical", "Horizontal", "Both"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		// @ts-ignore
		optionIcons: [
			"direction-vertical",
			"direction-horizontal",
			"direction-all",
		],
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/sK03TpIKzyq8OgUxM8Rl/4wCmjavOimoRcnzPAT5o/N3EKCZ7Fl.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var ChevronDownFonts = getFonts(stdin_default);
var enabledGestures = {
	fwVRCRWr7: {
		hover: true,
	},
	HkumzbVQH: {
		hover: true,
	},
};
var cycleOrder = ["HkumzbVQH", "fwVRCRWr7"];
var serializationHash = "framer-OpdMk";
var variantClassNames = {
	fwVRCRWr7: "framer-v-nvnn85",
	HkumzbVQH: "framer-v-18bryc7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Closed: "HkumzbVQH",
	Open: "fwVRCRWr7",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		T8rQFvSBR:
			answer ??
			props.T8rQFvSBR ??
			"You can learn Iman Gadzhi, Devin Jatho and Daniel Dalen style. There is option to request any style you need.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HkumzbVQH",
		W88zB8mIG: question ?? props.W88zB8mIG ?? "Question",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		W88zB8mIG: W88zB8mIG2,
		T8rQFvSBR: T8rQFvSBR2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HkumzbVQH",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap17pnvci = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("fwVRCRWr7");
	});
	const onTap1rzig0m = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("HkumzbVQH");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "fwVRCRWr7-hover") return true;
		if (baseVariant === "fwVRCRWr7") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-18bryc7",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"HkumzbVQH"}
						onTap={onTap17pnvci}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						variants={{
							"fwVRCRWr7-hover": {
								backgroundColor:
									"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(18, 18, 18))",
							},
							"HkumzbVQH-hover": {
								backgroundColor:
									"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(18, 18, 18))",
							},
						}}
						{...addPropertyOverrides(
							{
								"fwVRCRWr7-hover": {
									"data-framer-name": void 0,
								},
								"HkumzbVQH-hover": {
									"data-framer-name": void 0,
								},
								fwVRCRWr7: {
									"data-framer-name": "Open",
									onTap: onTap1rzig0m,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1ld7j9b"}
							data-framer-name={"Question"}
							layoutDependency={layoutDependency}
							layoutId={"QbKnXiLaZ"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-x39f3x"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"RxzoC9WNr"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--framer-paragraph-spacing": "0px",
								}}
								text={W88zB8mIG2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-xsql1q"}
										data-styles-preset={"Awxi1CAQQ"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255)))",
										}}
									>
										{"Question"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{_jsx2(stdin_default, {
								animated: true,
								className: "framer-tvvreq",
								layoutDependency,
								layoutId: "tZ0DVh1A5",
								style: {
									"--1m973uw":
										"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
									"--js9iwy": 2,
									rotate: 0,
								},
								variants: {
									"HkumzbVQH-hover": {
										rotate: 0,
									},
									fwVRCRWr7: {
										rotate: 180,
									},
								},
							})}
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-17g557d"}
								data-framer-name={"Answer"}
								layoutDependency={layoutDependency}
								layoutId={"MmjAcjgB9"}
								style={{
									opacity: 0,
								}}
								variants={{
									fwVRCRWr7: {
										opacity: 1,
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-a34mcm"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eWpMXiKeX"}
									style={{
										"--framer-paragraph-spacing": "0px",
										opacity: 0.6,
									}}
									text={T8rQFvSBR2}
									variants={{
										fwVRCRWr7: {
											opacity: 1,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-2io64c"}
											data-styles-preset={"AnqNoZ_U2"}
											dir={"auto"}
										>
											{
												"You can learn Iman Gadzhi, Devin Jatho and Daniel Dalen style. There is option to request any style you need."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OpdMk.framer-1xbk0s4, .framer-OpdMk .framer-1xbk0s4 { display: block; }",
	".framer-OpdMk.framer-18bryc7 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 480px; will-change: var(--framer-will-change-override, transform); }",
	".framer-OpdMk .framer-1ld7j9b { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 24px 16px 24px; position: relative; user-select: none; width: 100%; }",
	".framer-OpdMk .framer-x39f3x { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-OpdMk .framer-tvvreq { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-OpdMk .framer-17g557d { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 24px 20px 24px; position: relative; width: 100%; }",
	".framer-OpdMk .framer-a34mcm { --framer-text-wrap-override: balance; -webkit-user-select: none; flex: none; height: auto; max-width: 100%; position: relative; user-select: none; width: 100%; }",
	...css2,
	...css,
	'.framer-OpdMk[data-border="true"]::after, .framer-OpdMk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerN3EKCZ7Fl = withCSS(Component, css3, "framer-OpdMk");
var stdin_default2 = FramerN3EKCZ7Fl;
FramerN3EKCZ7Fl.displayName = "Faq";
FramerN3EKCZ7Fl.defaultProps = {
	height: 53,
	width: 480,
};
addPropertyControls2(FramerN3EKCZ7Fl, {
	variant: {
		options: ["HkumzbVQH", "fwVRCRWr7"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	W88zB8mIG: {
		defaultValue: "Question",
		displayTextArea: true,
		placeholder: "",
		title: "Question",
		type: ControlType2.String,
	},
	onW88zB8mIGChange: {
		changes: "W88zB8mIG",
		type: ControlType2.ChangeHandler,
	},
	T8rQFvSBR: {
		defaultValue:
			"You can learn Iman Gadzhi, Devin Jatho and Daniel Dalen style. There is option to request any style you need.",
		displayTextArea: true,
		placeholder: "",
		title: "Answer",
		type: ControlType2.String,
	},
	onT8rQFvSBRChange: {
		changes: "T8rQFvSBR",
		type: ControlType2.ChangeHandler,
	},
});
addFonts(
	FramerN3EKCZ7Fl,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ChevronDownFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/ajeCF25099Tfl6XN7DwZ/f9HGHMLVWTDraRDOZpz0/WNv4NxpCj.js
var LayoutJumpPreventerFonts = getFonts2(AvoidLayoutJumping);
var FaqFonts = getFonts2(stdin_default2);
var serializationHash2 = "framer-TEE1K";
var variantClassNames2 = {
	JjovphBqS: "framer-v-ypospe",
};
var transition12 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "JjovphBqS",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-ypospe",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"JjovphBqS"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-12vi086-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"NmNbm4Yh2-container"}
								nodeId={"NmNbm4Yh2"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"NmNbm4Yh2"}
									layoutId={"NmNbm4Yh2"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-qp7cg5-container"}
								layoutDependency={layoutDependency}
								layoutId={"p6rfJZC9M-container"}
								nodeId={"p6rfJZC9M"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "p6rfJZC9M",
									layoutId: "p6rfJZC9M",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"Yes! Cadence offers a free plan with essential features to help you boost your productivity. If you want advanced AI insights and more customization, you can upgrade to Pro or Lifetime.",
									variant: "fwVRCRWr7",
									W88zB8mIG: "Is Cadence really free to use?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 69}
						>
							<SmartComponentScopedContainer
								className={"framer-1jrt63p-container"}
								layoutDependency={layoutDependency}
								layoutId={"kkk3IOvJe-container"}
								nodeId={"kkk3IOvJe"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "kkk3IOvJe",
									layoutId: "kkk3IOvJe",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"The Free plan includes basic productivity tracking and AI insights, while the Pro plan unlocks unlimited reports, smart scheduling, and advanced analytics for deeper workflow optimization.",
									variant: "HkumzbVQH",
									W88zB8mIG: "What\u2019s the difference between Free and Pro?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 138}
						>
							<SmartComponentScopedContainer
								className={"framer-q5r5om-container"}
								layoutDependency={layoutDependency}
								layoutId={"kyvh9RDGZ-container"}
								nodeId={"kyvh9RDGZ"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "kyvh9RDGZ",
									layoutId: "kyvh9RDGZ",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"Yes! Pay once and get lifetime access to all Pro features, including future updates\u2014no subscriptions, no hidden fees.",
									variant: "HkumzbVQH",
									W88zB8mIG: "Is the Lifetime plan a one-time payment?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 207}
						>
							<SmartComponentScopedContainer
								className={"framer-k4tkqc-container"}
								layoutDependency={layoutDependency}
								layoutId={"ahJWzp_g6-container"}
								nodeId={"ahJWzp_g6"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "ahJWzp_g6",
									layoutId: "ahJWzp_g6",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"Absolutely. You can cancel your Pro subscription anytime, and you\u2019ll still have access to the features until the end of your billing cycle.",
									variant: "HkumzbVQH",
									W88zB8mIG: "Can I cancel my subscription anytime?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 276}
						>
							<SmartComponentScopedContainer
								className={"framer-9f2thb-container"}
								layoutDependency={layoutDependency}
								layoutId={"SZis0OWzz-container"}
								nodeId={"SZis0OWzz"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "SZis0OWzz",
									layoutId: "SZis0OWzz",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"Yes! Cadence syncs seamlessly across all your devices, whether you\u2019re using a phone, tablet, or computer.",
									variant: "HkumzbVQH",
									W88zB8mIG: "Does Cadence work on all devices?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={53}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 345}
						>
							<SmartComponentScopedContainer
								className={"framer-1bjlwkl-container"}
								layoutDependency={layoutDependency}
								layoutId={"Ux144yZ7M-container"}
								nodeId={"Ux144yZ7M"}
								rendersWithMotion={true}
								scopeId={"WNv4NxpCj"}
							>
								{_jsx3(stdin_default2, {
									height: "100%",
									id: "Ux144yZ7M",
									layoutId: "Ux144yZ7M",
									style: {
										width: "100%",
									},
									T8rQFvSBR:
										"Yes, we offer a 30-day money-back guarantee on all Pro and Lifetime purchases. If you\u2019re not satisfied, contact us, and we\u2019ll refund your payment\u2014no questions asked.",
									variant: "HkumzbVQH",
									W88zB8mIG: "Do you offer refunds?",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TEE1K.framer-uz0ros, .framer-TEE1K .framer-uz0ros { display: block; }",
	".framer-TEE1K.framer-ypospe { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 680px; }",
	".framer-TEE1K .framer-12vi086-container { flex: none; height: auto; left: -2px; position: absolute; top: -5px; width: auto; z-index: 1; }",
	".framer-TEE1K .framer-qp7cg5-container, .framer-TEE1K .framer-1jrt63p-container, .framer-TEE1K .framer-q5r5om-container, .framer-TEE1K .framer-k4tkqc-container, .framer-TEE1K .framer-9f2thb-container, .framer-TEE1K .framer-1bjlwkl-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerWNv4NxpCj = withCSS2(Component2, css4, "framer-TEE1K");
var stdin_default3 = FramerWNv4NxpCj;
FramerWNv4NxpCj.displayName = "Accordion";
FramerWNv4NxpCj.defaultProps = {
	height: 471.5,
	width: 680,
};
addFonts2(
	FramerWNv4NxpCj,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...FaqFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
