// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Filled' | 'Outline' | 'Ghost' // Variant
 * text?: string // Text
 * onH9fdquxmOCHange?: any // onH9fdquxmOCHange
 * link?: string // Link
 * newTab?: boolean // New Tab
 * onuFNDRhDvWCHange?: any // onuFNDRhDvWCHange
 * smoothScroll?: boolean // Smooth Scroll
 * onqZfHbmzQfChange?: any // onqZfHbmzQfChange
 * trackingID?: any // Tracking ID
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-K3KYO637.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mpQYiENuMTYZfev7Nl5Q/rTgUten2SuQddSD42t4l/RrS411mD0.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	Fbxwx_O9x: {
		hover: true,
	},
	n1t5mNkfc: {
		hover: true,
	},
	Y1ageSf63: {
		hover: true,
	},
};
var cycleOrder = ["Y1ageSf63", "n1t5mNkfc", "Fbxwx_O9x"];
var serializationHash = "framer-FJpBA";
var variantClassNames = {
	Fbxwx_O9x: "framer-v-125hd7d",
	n1t5mNkfc: "framer-v-10g26xp",
	Y1ageSf63: "framer-v-17k9y98",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Filled: "Y1ageSf63",
	Ghost: "Fbxwx_O9x",
	Outline: "n1t5mNkfc",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	link,
	newTab,
	smoothScroll,
	text,
	trackingID,
	width,
	...props
}) => {
	return {
		...props,
		H9fdquxmO: text ?? props.H9fdquxmO ?? "Get started",
		qa2d0SHwc: link ?? props.qa2d0SHwc,
		qZfHbmzQf: smoothScroll ?? props.qZfHbmzQf ?? true,
		uFNDrhDvW: newTab ?? props.uFNDrhDvW ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Y1ageSf63",
		WqF2Pzc7v: trackingID ?? props.WqF2Pzc7v,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		H9fdquxmO: H9fdquxmO2,
		qa2d0SHwc: qa2d0SHwc2,
		uFNDrhDvW: uFNDrhDvW2,
		qZfHbmzQf: qZfHbmzQf2,
		WqF2Pzc7v: WqF2Pzc7v2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Y1ageSf63",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						clickTrackingId={WqF2Pzc7v2}
						href={qa2d0SHwc2}
						motionChild={true}
						nodeId={"Y1ageSf63"}
						openInNewTab={uFNDrhDvW2}
						scopeId={"RrS411mD0"}
						smoothScroll={qZfHbmzQf2}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-17k9y98", className2, classNames)} framer-12u7a91`}
							data-border={true}
							data-framer-name={"Filled"}
							layoutDependency={layoutDependency}
							layoutId={"Y1ageSf63"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "2px",
								"--border-color": "rgba(255, 255, 255, 0.12)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								backdropFilter: "none",
								backgroundColor:
									"var(--token-33937e6f-dc3e-4c47-bf83-7d83f61531ea, rgb(255, 255, 255))",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow: "0px 0px 34px 0px rgba(48, 100, 255, 0.1)",
								WebkitBackdropFilter: "none",
								...style,
							}}
							variants={{
								"Fbxwx_O9x-hover": {
									backgroundColor: "rgba(48, 100, 255, 0.1)",
								},
								"n1t5mNkfc-hover": {
									"--border-color": "rgba(255, 255, 255, 0.2)",
									backgroundColor: "rgba(26, 26, 26, 0.4)",
								},
								"Y1ageSf63-hover": {
									"--border-color": "rgba(255, 255, 255, 0.24)",
									backdropFilter: "none",
									boxShadow: "0px 0px 34px 0px rgba(48, 100, 255, 0.3)",
									WebkitBackdropFilter: "none",
								},
								Fbxwx_O9x: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backdropFilter: "blur(12px)",
									backgroundColor: "rgba(26, 26, 26, 0.01)",
									boxShadow: "none",
									WebkitBackdropFilter: "blur(12px)",
								},
								n1t5mNkfc: {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-top-width": "1px",
									backdropFilter: "blur(12px)",
									backgroundColor: "rgba(26, 26, 26, 0.01)",
									boxShadow: "none",
									WebkitBackdropFilter: "blur(12px)",
								},
							}}
							{...addPropertyOverrides(
								{
									"Fbxwx_O9x-hover": {
										"data-framer-name": void 0,
									},
									"n1t5mNkfc-hover": {
										"data-framer-name": void 0,
									},
									"Y1ageSf63-hover": {
										"data-framer-name": void 0,
									},
									Fbxwx_O9x: {
										"data-framer-name": "Ghost",
									},
									n1t5mNkfc: {
										"data-framer-name": "Outline",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1a4l70o"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"iiVRZfBRQ"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={H9fdquxmO2}
								variants={{
									Fbxwx_O9x: {
										"--extracted-r6o4lv":
											"var(--token-33937e6f-dc3e-4c47-bf83-7d83f61531ea, rgb(48, 100, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										Fbxwx_O9x: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-9fs3sz"}
														data-styles-preset={"GxHDpGVa7"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-33937e6f-dc3e-4c47-bf83-7d83f61531ea, rgb(48, 100, 255)))",
														}}
													>
														{"Get started"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-9fs3sz"}
										data-styles-preset={"GxHDpGVa7"}
										dir={"auto"}
									>
										{"Get started"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FJpBA.framer-12u7a91, .framer-FJpBA .framer-12u7a91 { display: block; }",
	".framer-FJpBA.framer-17k9y98 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 48px; justify-content: center; overflow: hidden; padding: 16px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-FJpBA .framer-1a4l70o { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-FJpBA.framer-v-125hd7d.framer-17k9y98 { height: 32px; padding: 8px; }",
	...css,
	'.framer-FJpBA[data-border="true"]::after, .framer-FJpBA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerRrS411mD0 = withCSS(Component, css2, "framer-FJpBA");
var stdin_default = FramerRrS411mD0;
FramerRrS411mD0.displayName = "Button";
FramerRrS411mD0.defaultProps = {
	height: 48,
	width: 119,
};
addPropertyControls(FramerRrS411mD0, {
	variant: {
		options: ["Y1ageSf63", "n1t5mNkfc", "Fbxwx_O9x"],
		optionTitles: ["Filled", "Outline", "Ghost"],
		title: "Variant",
		type: ControlType.Enum,
	},
	H9fdquxmO: {
		defaultValue: "Get started",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	onH9fdquxmOChange: {
		changes: "H9fdquxmO",
		type: ControlType.ChangeHandler,
	},
	qa2d0SHwc: {
		title: "Link",
		type: ControlType.Link,
	},
	uFNDrhDvW: {
		defaultValue: true,
		title: "New Tab",
		type: ControlType.Boolean,
	},
	onuFNDrhDvWChange: {
		changes: "uFNDrhDvW",
		type: ControlType.ChangeHandler,
	},
	qZfHbmzQf: {
		defaultValue: true,
		title: "Smooth Scroll",
		type: ControlType.Boolean,
	},
	onqZfHbmzQfChange: {
		changes: "qZfHbmzQf",
		type: ControlType.ChangeHandler,
	},
	WqF2Pzc7v: {
		title: "Tracking ID",
		type: ControlType.TrackingId,
	},
});
addFonts(
	FramerRrS411mD0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "n1t5mNkfc",
	xl: "Fbxwx_O9x",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
