// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * icon?: any // Icon
 * title?: string // Title
 * onE5hH6Ww9kChange?: any // onE5hH6Ww9kChange
 * description?: string // Description
 * onoJ0nKFCw9Change?: any // onoJ0nKFCw9Change
}} Props

 */
import { stdin_default } from "./chunks/chunk-BDE5Q2MY.js";
import { className, css, fonts } from "./chunks/chunk-2HMR454I.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-K3KYO637.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4xDsgWqJ0eijbEPLPqX3/Gmyz6gCsdoM56rDfEhZ4/Vqnpxuz_F.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-CKnPq";
var variantClassNames = {
	pGygTRxnM: "framer-v-15kq94f",
};
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.12, 0.23, 0.38, 0.98],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ description, height, icon, id, title, width, ...props }) => {
	return {
		...props,
		E5hH6Ww9k: title ?? props.E5hH6Ww9k ?? "Maximum Security",
		ILLSsnIrF: icon ?? props.ILLSsnIrF ?? stdin_default,
		oJ0nKFcw9:
			description ??
			props.oJ0nKFcw9 ??
			"Your assets are protected with cutting-edge security protocols.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ILLSsnIrF: ILLSsnIrF2,
		E5hH6Ww9k: E5hH6Ww9k2,
		oJ0nKFcw9: oJ0nKFcw92,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "pGygTRxnM",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-15kq94f",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"pGygTRxnM"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(3, 3, 3))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							boxShadow: "inset 0px 0px 46px 0px rgba(255, 255, 255, 0)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1hb1eqe"}
							data-border={true}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"PvKyt4gP8"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(95, 95, 113, 0.22)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 50,
								borderBottomRightRadius: 50,
								borderTopLeftRadius: 50,
								borderTopRightRadius: 50,
							}}
						>
							<Instance
								animated={true}
								className={"framer-13jetqa"}
								Component={ILLSsnIrF2}
								layoutDependency={layoutDependency}
								layoutId={"z5YFaOk_Z"}
								style={{
									"--1m973uw":
										"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
									"--js9iwy": 2,
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-lfgpsu"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"wE2KJTau1"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-wloh1u"}
								data-framer-name={"Maximum Security"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"T_OrmxTbh"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={E5hH6Ww9k2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-9fs3sz"}
										data-styles-preset={"GxHDpGVa7"}
										dir={"auto"}
									>
										{"Maximum Security"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-16igyyj"}
								data-framer-name={
									"Your assets are protected with cutting-edge security protocols."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"HuVRCtDQv"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={oJ0nKFcw92}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-xsql1q"}
										data-styles-preset={"Awxi1CAQQ"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{
											"Your assets are protected with cutting-edge security protocols."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CKnPq.framer-33z66r, .framer-CKnPq .framer-33z66r { display: block; }",
	".framer-CKnPq.framer-15kq94f { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 20px; position: relative; width: 296px; will-change: var(--framer-will-change-override, transform); }",
	".framer-CKnPq .framer-1hb1eqe { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 64px; justify-content: center; overflow: hidden; padding: 2px 3px 2px 3px; position: relative; width: 64px; will-change: var(--framer-will-change-override, transform); }",
	".framer-CKnPq .framer-13jetqa { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-CKnPq .framer-lfgpsu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-CKnPq .framer-wloh1u { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-CKnPq .framer-16igyyj { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	...css2,
	...css,
	'.framer-CKnPq[data-border="true"]::after, .framer-CKnPq [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerVqnpxuz_F = withCSS(Component, css3, "framer-CKnPq");
var stdin_default2 = FramerVqnpxuz_F;
FramerVqnpxuz_F.displayName = "Card";
FramerVqnpxuz_F.defaultProps = {
	height: 197,
	width: 296,
};
addPropertyControls(FramerVqnpxuz_F, {
	ILLSsnIrF: {
		defaultValue: {
			identifier:
				"module:UE8WWbLIUmyibNWAKTzx/zNv6U8II9zcgtQVzuGUU/WQgmZvDvc.js:default",
			moduleId: "UE8WWbLIUmyibNWAKTzx",
		},
		setModuleId: "Y7SpbVH16cWqMhj75z1M",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
	E5hH6Ww9k: {
		defaultValue: "Maximum Security",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onE5hH6Ww9kChange: {
		changes: "E5hH6Ww9k",
		type: ControlType.ChangeHandler,
	},
	oJ0nKFcw9: {
		defaultValue:
			"Your assets are protected with cutting-edge security protocols.",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	onoJ0nKFcw9Change: {
		changes: "oJ0nKFcw9",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerVqnpxuz_F,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var card_default = ComponentWithRoot;
export { card_default as default };
