// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Active' // Variant
 * icon?: any // Icon
 * text?: string // Text
 * onyxGK5lOXTCHange?: any // onyxGK5lOXTCHange
 * click?: Function // Click
}} Props

 */
import { stdin_default } from "./chunks/chunk-BDE5Q2MY.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NTQNEBCY.js";
import { className, css, fonts } from "./chunks/chunk-URGOVI2W.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:chip
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tS329kDYs0FYc2P3ybTt/kUL0pnPBe3CZ0DzlgNoK/Ig4LYNR2I.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	fFWaboF5d: {
		hover: true,
	},
};
var cycleOrder = ["fFWaboF5d", "zIyvfaguP"];
var serializationHash = "framer-5HTpt";
var variantClassNames = {
	fFWaboF5d: "framer-v-nkvo40",
	zIyvfaguP: "framer-v-1451j8v",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Active: "zIyvfaguP",
	Default: "fFWaboF5d",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, icon, id, text, width, ...props }) => {
	return {
		...props,
		tSHGITUhm: click ?? props.tSHGITUhm,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fFWaboF5d",
		yWSITaK0o: icon ?? props.yWSITaK0o ?? stdin_default,
		yxGK5lOXT: text ?? props.yxGK5lOXT ?? "Smart Task Prioritization",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		yWSITaK0o: yWSITaK0o2,
		yxGK5lOXT: yxGK5lOXT2,
		tSHGITUhm: tSHGITUhm2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fFWaboF5d",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1hsqc22 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (tSHGITUhm2) {
			const res = await tSHGITUhm2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							zIyvfaguP: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-nkvo40",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"fFWaboF5d"}
						onTap={onTap1hsqc22}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor: "rgb(0, 0, 0)",
							borderBottomLeftRadius: 48,
							borderBottomRightRadius: 48,
							borderTopLeftRadius: 48,
							borderTopRightRadius: 48,
							...style,
						}}
						variants={{
							"fFWaboF5d-hover": {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(3, 3, 3))",
							},
							zIyvfaguP: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(3, 3, 3))",
							},
						}}
						{...addPropertyOverrides(
							{
								"fFWaboF5d-hover": {
									"data-framer-name": void 0,
								},
								zIyvfaguP: {
									"data-border": true,
									"data-framer-name": "Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Instance
							animated={true}
							className={"framer-1p7nug1"}
							Component={yWSITaK0o2}
							layoutDependency={layoutDependency}
							layoutId={"xvuNXZWO1"}
							style={{
								"--1m973uw":
									"var(--token-5d3602f5-d470-4b4b-916d-5b57bbf588f8, rgba(255, 255, 255, 0.8))",
								"--js9iwy": 1.5,
							}}
							variants={{
								zIyvfaguP: {
									"--1m973uw":
										"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
								},
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ym5z5r"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"cXxUUpUfV"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={yxGK5lOXT2}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									zIyvfaguP: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-z5yjcz"}
													data-styles-preset={"I1dFaNZDG"}
													dir={"auto"}
												>
													{"Smart Task Prioritization"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-2io64c"}
									data-styles-preset={"AnqNoZ_U2"}
									dir={"auto"}
								>
									{"Smart Task Prioritization"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5HTpt.framer-1gisou, .framer-5HTpt .framer-1gisou { display: block; }",
	".framer-5HTpt.framer-nkvo40 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 12px 8px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-5HTpt .framer-1p7nug1 { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-5HTpt .framer-ym5z5r { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
	...css2,
	'.framer-5HTpt[data-border="true"]::after, .framer-5HTpt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerIg4LYNR2I = withCSS(Component, css3, "framer-5HTpt");
var stdin_default2 = FramerIg4LYNR2I;
FramerIg4LYNR2I.displayName = "Chip";
FramerIg4LYNR2I.defaultProps = {
	height: 34,
	width: 202,
};
addPropertyControls(FramerIg4LYNR2I, {
	variant: {
		options: ["fFWaboF5d", "zIyvfaguP"],
		optionTitles: ["Default", "Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
	yWSITaK0o: {
		defaultValue: {
			identifier:
				"module:UE8WWbLIUmyibNWAKTzx/zNv6U8II9zcgtQVzuGUU/WQgmZvDvc.js:default",
			moduleId: "UE8WWbLIUmyibNWAKTzx",
		},
		setModuleId: "Y7SpbVH16cWqMhj75z1M",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
	yxGK5lOXT: {
		defaultValue: "Smart Task Prioritization",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	onyxGK5lOXTChange: {
		changes: "yxGK5lOXT",
		type: ControlType.ChangeHandler,
	},
	tSHGITUhm: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerIg4LYNR2I,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:chip
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "fFWaboF5d",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ChipFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var chip_default = ComponentWithRoot;
export { chip_default as default };
