// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Main (Change this)' | 'Task Prioritization' | 'Focus Mode' | 'Minimal Planner' | 'Unified Workspace' | 'Progress Tracking' // Variant
}} Props

 */
import {
	stdin_default,
	stdin_default2,
	stdin_default3,
	stdin_default4,
	stdin_default5,
	stdin_default6,
} from "./chunks/chunk-IYJX6KNH.js";
import "./chunks/chunk-BDE5Q2MY.js";
import { className, css, fonts } from "./chunks/chunk-2HMR454I.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WOTVKQ2B.js";
import { stdin_default as stdin_default7 } from "./chunks/chunk-XMJR4DGB.js";
import "./chunks/chunk-K3KYO637.js";
import "./chunks/chunk-NTQNEBCY.js";
import "./chunks/chunk-URGOVI2W.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:features-desktop
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3CYy7NCTW7F3SRX410Vw/lnx5l9WQduUDNX7UCzBJ/NmtswHhYq.js
import { jsx as _jsx6, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls6,
	ComponentViewportProvider,
	ControlType as ControlType6,
	cx as cx6,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS6,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion as motion6, MotionConfigContext } from "unframer";
import * as React6 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/AOATdCdjVYtj8BB9p633/N9ChTUGAI5essMxs37aE/tFm8aYiPg.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 0 16 C 0 17.105 0.895 18 2 18 L 18 18" fill="transparent" height="18px" id="LvzYPp4o5" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 3)" width="18px"/><path d="M 12 0 L 7 5 L 3 1 L 0 4" fill="transparent" height="5px" id="sDpfhR4ud" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(7 9)" width="12px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("1320102016", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-48TqL", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css3 = [
	`.framer-48TqL { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-48TqL");
Icon.displayName = "Chart Line";
var stdin_default8 = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/ekIobvgL8K0ruDxSZNBs/eE5G5vYsep3u0YSDnJxg/ZaQCWVpdg.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var mask2 = "var(--framer-icon-mask)";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG2>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 10 C 0 4.477 4.477 0 10 0 C 15.523 0 20 4.477 20 10 C 20 15.523 15.523 20 10 20 C 4.477 20 0 15.523 0 10 Z" fill="transparent" height="20px" id="pRSXITd2A" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(2 2)" width="20px"/><path d="M 0 6 C 0 2.686 2.686 0 6 0 C 9.314 0 12 2.686 12 6 C 12 9.314 9.314 12 6 12 C 2.686 12 0 9.314 0 6 Z" fill="transparent" height="12px" id="oY8CBr2By" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(6 6)" width="12px"/><path d="M 0 2 C 0 0.895 0.895 0 2 0 C 3.105 0 4 0.895 4 2 C 4 3.105 3.105 4 2 4 C 0.895 4 0 3.105 0 2 Z" fill="transparent" height="4px" id="H_pN1jqUm" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(10 10)" width="4px"/></svg>';
var getProps2 = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("3039211863", svg2);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-WeVEd", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG2>
	);
});
var css4 = [
	`.framer-WeVEd { -webkit-mask: ${mask2}; aspect-ratio: 1; display: block; mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css4, "framer-WeVEd");
Icon2.displayName = "Target";
var stdin_default9 = Icon2;
addPropertyControls2(Icon2, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/Kz8DxKqLfluRS5AniynC/443JmlmMr9YmxjYwgduW/II0fEI58d.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	motion as motion3,
	useSVGTemplate as useSVGTemplate3,
	withCSS as withCSS3,
} from "unframer";
import * as React3 from "react";
import { forwardRef as forwardRef6 } from "react";
var mask3 = "var(--framer-icon-mask)";
var Base3 = /* @__PURE__ */ forwardRef6(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG3 = motion3.create(Base3);
var SVG3 = /* @__PURE__ */ forwardRef6((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG3 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG3>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg3 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.391 2.39 C 13.647 2.646 14.021 2.744 14.37 2.646 C 14.718 2.547 14.987 2.268 15.071 1.916 C 15.358 0.72 16.472 -0.089 17.698 0.008 C 18.924 0.104 19.898 1.078 19.994 2.304 C 20.09 3.53 19.281 4.644 18.085 4.931 C 17.733 5.015 17.454 5.284 17.355 5.632 C 17.257 5.981 17.355 6.355 17.611 6.611 L 19.294 8.293 C 19.747 8.746 20.001 9.36 20.001 10 C 20.001 10.64 19.747 11.254 19.294 11.707 L 17.611 13.39 C 17.355 13.646 16.98 13.744 16.632 13.646 C 16.283 13.547 16.015 13.268 15.931 12.916 C 15.644 11.72 14.529 10.911 13.304 11.008 C 12.078 11.104 11.104 12.078 11.008 13.304 C 10.911 14.53 11.721 15.644 12.917 15.931 C 13.269 16.015 13.548 16.284 13.647 16.632 C 13.745 16.981 13.647 17.355 13.391 17.611 L 11.708 19.293 C 11.255 19.746 10.641 20 10.001 20 C 9.361 20 8.747 19.746 8.294 19.293 L 6.611 17.61 C 6.355 17.354 5.98 17.256 5.632 17.354 C 5.283 17.453 5.015 17.732 4.931 18.084 C 4.644 19.28 3.529 20.089 2.304 19.992 C 1.078 19.896 0.104 18.922 0.008 17.696 C -0.089 16.47 0.721 15.356 1.917 15.069 C 2.269 14.985 2.548 14.717 2.647 14.368 C 2.745 14.02 2.647 13.645 2.391 13.389 L 0.708 11.707 C 0.255 11.254 0.001 10.64 0.001 10 C 0.001 9.36 0.255 8.746 0.708 8.293 L 2.391 6.61 C 2.647 6.354 3.021 6.256 3.37 6.354 C 3.718 6.453 3.987 6.732 4.071 7.084 C 4.358 8.28 5.472 9.089 6.698 8.992 C 7.924 8.896 8.898 7.922 8.994 6.696 C 9.09 5.47 8.281 4.356 7.085 4.069 C 6.733 3.985 6.454 3.717 6.355 3.368 C 6.257 3.02 6.355 2.645 6.611 2.389 L 8.294 0.707 C 8.747 0.254 9.361 0 10.001 0 C 10.641 0 11.255 0.254 11.708 0.707 Z" fill="transparent" height="20.00022930625534px" id="lcumEQqO7" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(1.999 2)" width="20.0018410081775px"/></svg>';
var getProps3 = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps3(props);
	const href = useSVGTemplate3("2251375615", svg3);
	return (
		<SVG3
			{...restProps}
			className={cx3("framer-lOEnl", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG3>
	);
});
var css5 = [
	`.framer-lOEnl { -webkit-mask: ${mask3}; aspect-ratio: 1; display: block; mask: ${mask3}; width: 24px; }`,
];
var Icon3 = withCSS3(Component3, css5, "framer-lOEnl");
Icon3.displayName = "Puzzle";
var stdin_default10 = Icon3;
addPropertyControls3(Icon3, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType3.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType3.Number,
	},
});

// /:https://framerusercontent.com/modules/LnEqQQ2EddyT1eyD82Qf/ibU6IuGxCzulfZgNbVp9/PZz_Pa1pM.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls4,
	ControlType as ControlType4,
	cx as cx4,
	motion as motion4,
	useSVGTemplate as useSVGTemplate4,
	withCSS as withCSS4,
} from "unframer";
import * as React4 from "react";
import { forwardRef as forwardRef8 } from "react";
var mask4 = "var(--framer-icon-mask)";
var Base4 = /* @__PURE__ */ forwardRef8(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG4 = motion4.create(Base4);
var SVG4 = /* @__PURE__ */ forwardRef8((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG4 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG4>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg4 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 0 4" fill="transparent" height="4px" id="PimSI8EkH" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(8 2)" width="1px"/><path d="M 0 0 L 0 4" fill="transparent" height="4px" id="aUP_qLROX" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(16 2)" width="1px"/><path d="M 2 18 C 0.895 18 0 17.105 0 16 L 0 2 C 0 0.895 0.895 0 2 0 L 16 0 C 17.105 0 18 0.895 18 2 L 18 16 C 18 17.105 17.105 18 16 18 Z" fill="transparent" height="18px" id="et6dD8IXx" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 4)" width="18px"/><path d="M 0 0 L 18 0" fill="transparent" height="1px" id="nVWw9AjMG" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 10)" width="18px"/></svg>';
var getProps4 = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps4(props);
	const href = useSVGTemplate4("2066690328", svg4);
	return (
		<SVG4
			{...restProps}
			className={cx4("framer-vAXF2", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG4>
	);
});
var css6 = [
	`.framer-vAXF2 { -webkit-mask: ${mask4}; aspect-ratio: 1; display: block; mask: ${mask4}; width: 24px; }`,
];
var Icon4 = withCSS4(Component4, css6, "framer-vAXF2");
Icon4.displayName = "Calendar";
var stdin_default11 = Icon4;
addPropertyControls4(Icon4, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType4.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType4.Number,
	},
});

// /:https://framerusercontent.com/modules/nheutavr9yHj19APoTSX/87OgXwZoYv8SSQHzQtbl/kYuPD1Dlv.js
import { jsx as _jsx5 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls5,
	ControlType as ControlType5,
	cx as cx5,
	motion as motion5,
	useSVGTemplate as useSVGTemplate5,
	withCSS as withCSS5,
} from "unframer";
import * as React5 from "react";
import { forwardRef as forwardRef10 } from "react";
var mask5 = "var(--framer-icon-mask)";
var Base5 = /* @__PURE__ */ forwardRef10(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG5 = motion5.create(Base5);
var SVG5 = /* @__PURE__ */ forwardRef10((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG5 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG5>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg5 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 8 0" fill="transparent" height="1px" id="APEG6Q7nj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(13 5)" width="8px"/><path d="M 0 0 L 8 0" fill="transparent" height="1px" id="j9eT0h2mX" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(13 12)" width="8px"/><path d="M 0 0 L 8 0" fill="transparent" height="1px" id="bcqZCEbUb" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(13 19)" width="8px"/><path d="M 0 2 L 2 4 L 6 0" fill="transparent" height="4px" id="dDaJT3aRB" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 15)" width="6px"/><path d="M 0 2 L 2 4 L 6 0" fill="transparent" height="4px" id="de7RC4gOr" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 5)" width="6px"/></svg>';
var getProps5 = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps5(props);
	const href = useSVGTemplate5("1440315036", svg5);
	return (
		<SVG5
			{...restProps}
			className={cx5("framer-1keEK", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG5>
	);
});
var css7 = [
	`.framer-1keEK { -webkit-mask: ${mask5}; aspect-ratio: 1; display: block; mask: ${mask5}; width: 24px; }`,
];
var Icon5 = withCSS5(Component5, css7, "framer-1keEK");
Icon5.displayName = "List Checks";
var stdin_default12 = Icon5;
addPropertyControls5(Icon5, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType5.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType5.Number,
	},
});

// /:https://framerusercontent.com/modules/3CYy7NCTW7F3SRX410Vw/lnx5l9WQduUDNX7UCzBJ/NmtswHhYq.js
var ChipFonts = getFonts(stdin_default6);
var Image1WithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image1),
);
var ButtonFonts = getFonts(stdin_default7);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion6.div),
);
var cycleOrder = [
	"xVfgwnkh3",
	"zmBSKyFdr",
	"qU7hT9U2_",
	"TPHAAZT5B",
	"khS0PpTZ5",
	"eGTgp2d_M",
];
var serializationHash = "framer-Guqct";
var variantClassNames = {
	eGTgp2d_M: "framer-v-12jk3zs",
	khS0PpTZ5: "framer-v-bhn5mz",
	qU7hT9U2_: "framer-v-aye3bm",
	TPHAAZT5B: "framer-v-17737v9",
	xVfgwnkh3: "framer-v-2okwsd",
	zmBSKyFdr: "framer-v-tsuxo6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.12, 0.23, 0.17, 0.99],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var animation2 = {
	filter: "blur(4px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 12,
};
var transition3 = {
	delay: 0.05,
	duration: 0.8,
	ease: [0.12, 0.23, 0.17, 0.98],
	type: "tween",
};
var textEffect = {
	effect: animation2,
	repeat: false,
	startDelay: 0,
	threshold: 0.5,
	tokenization: "line",
	transition: transition3,
	trigger: "onInView",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React6.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React6.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Focus Mode": "qU7hT9U2_",
	"Main (Change this)": "xVfgwnkh3",
	"Minimal Planner": "TPHAAZT5B",
	"Progress Tracking": "eGTgp2d_M",
	"Task Prioritization": "zmBSKyFdr",
	"Unified Workspace": "khS0PpTZ5",
};
var Variants = motion6.create(React6.Fragment);
var getProps6 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "xVfgwnkh3",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component6 = /* @__PURE__ */ React6.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React6.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps6(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "xVfgwnkh3",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const tSHGITUhml91g52 = activeVariantCallback(async (...args) => {
		setVariant("zmBSKyFdr");
	});
	const tSHGITUhm19ucnjc = activeVariantCallback(async (...args) => {
		setVariant("qU7hT9U2_");
	});
	const tSHGITUhm1hfcobm = activeVariantCallback(async (...args) => {
		setVariant("TPHAAZT5B");
	});
	const tSHGITUhmsrqira = activeVariantCallback(async (...args) => {
		setVariant("khS0PpTZ5");
	});
	const tSHGITUhmjcsb6v = activeVariantCallback(async (...args) => {
		setVariant("eGTgp2d_M");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx6(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["qU7hT9U2_", "TPHAAZT5B", "khS0PpTZ5", "eGTgp2d_M"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (
			["zmBSKyFdr", "TPHAAZT5B", "khS0PpTZ5", "eGTgp2d_M"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (
			["zmBSKyFdr", "qU7hT9U2_", "khS0PpTZ5", "eGTgp2d_M"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (
			["zmBSKyFdr", "qU7hT9U2_", "TPHAAZT5B", "eGTgp2d_M"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed4 = () => {
		if (
			["zmBSKyFdr", "qU7hT9U2_", "TPHAAZT5B", "khS0PpTZ5"].includes(baseVariant)
		)
			return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion6.div
						{...restProps}
						{...gestureHandlers}
						className={cx6(
							scopingClassNames,
							"framer-2okwsd",
							className3,
							classNames,
						)}
						data-framer-name={"Main (Change this)"}
						layoutDependency={layoutDependency}
						layoutId={"xVfgwnkh3"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								eGTgp2d_M: {
									"data-framer-name": "Progress Tracking",
								},
								khS0PpTZ5: {
									"data-framer-name": "Unified Workspace",
								},
								qU7hT9U2_: {
									"data-framer-name": "Focus Mode",
								},
								TPHAAZT5B: {
									"data-framer-name": "Minimal Planner",
								},
								zmBSKyFdr: {
									"data-framer-name": "Task Prioritization",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion6.div
							className={"framer-1ifcwlt"}
							data-framer-name={"ChipsList"}
							layoutDependency={layoutDependency}
							layoutId={"NgPJ94olp"}
						>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-ga0jyi-container"}
									layoutDependency={layoutDependency}
									layoutId={"sj0E6FC4E-container"}
									nodeId={"sj0E6FC4E"}
									rendersWithMotion={true}
									scopeId={"NmtswHhYq"}
								>
									{_jsx6(stdin_default6, {
										height: "100%",
										id: "sj0E6FC4E",
										layoutId: "sj0E6FC4E",
										QYzJ5sW1W: stdin_default,
										tSHGITUhm: tSHGITUhml91g52,
										variant: matchVariant("zIyvfaguP"),
										width: "100%",
										yWSITaK0o: stdin_default12,
										yxGK5lOXT: "Task Prioritization",
										...addPropertyOverrides(
											{
												eGTgp2d_M: {
													variant: matchVariant("fFWaboF5d"),
												},
												khS0PpTZ5: {
													variant: matchVariant("fFWaboF5d"),
												},
												qU7hT9U2_: {
													variant: matchVariant("fFWaboF5d"),
												},
												TPHAAZT5B: {
													variant: matchVariant("fFWaboF5d"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-1p0tjdf-container"}
									layoutDependency={layoutDependency}
									layoutId={"lAaM9z5jq-container"}
									nodeId={"lAaM9z5jq"}
									rendersWithMotion={true}
									scopeId={"NmtswHhYq"}
								>
									{_jsx6(stdin_default6, {
										height: "100%",
										id: "lAaM9z5jq",
										layoutId: "lAaM9z5jq",
										QYzJ5sW1W: stdin_default3,
										tSHGITUhm: tSHGITUhm19ucnjc,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yWSITaK0o: stdin_default9,
										yxGK5lOXT: "Focus Mode",
										...addPropertyOverrides(
											{
												qU7hT9U2_: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-1rsa34-container"}
									layoutDependency={layoutDependency}
									layoutId={"b08Db5obi-container"}
									nodeId={"b08Db5obi"}
									rendersWithMotion={true}
									scopeId={"NmtswHhYq"}
								>
									{_jsx6(stdin_default6, {
										height: "100%",
										id: "b08Db5obi",
										layoutId: "b08Db5obi",
										QYzJ5sW1W: stdin_default4,
										tSHGITUhm: tSHGITUhm1hfcobm,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yWSITaK0o: stdin_default11,
										yxGK5lOXT: "Minimal Planner",
										...addPropertyOverrides(
											{
												TPHAAZT5B: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-ysc0b2-container"}
									layoutDependency={layoutDependency}
									layoutId={"OcmrUP2wM-container"}
									nodeId={"OcmrUP2wM"}
									rendersWithMotion={true}
									scopeId={"NmtswHhYq"}
								>
									{_jsx6(stdin_default6, {
										height: "100%",
										id: "OcmrUP2wM",
										layoutId: "OcmrUP2wM",
										QYzJ5sW1W: stdin_default5,
										tSHGITUhm: tSHGITUhmsrqira,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yWSITaK0o: stdin_default10,
										yxGK5lOXT: "Unified Workspace",
										...addPropertyOverrides(
											{
												khS0PpTZ5: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-n8zyxg-container"}
									layoutDependency={layoutDependency}
									layoutId={"DOo5DhP6L-container"}
									nodeId={"DOo5DhP6L"}
									rendersWithMotion={true}
									scopeId={"NmtswHhYq"}
								>
									{_jsx6(stdin_default6, {
										height: "100%",
										id: "DOo5DhP6L",
										layoutId: "DOo5DhP6L",
										QYzJ5sW1W: stdin_default2,
										tSHGITUhm: tSHGITUhmjcsb6v,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yWSITaK0o: stdin_default8,
										yxGK5lOXT: "Progress Tracking",
										...addPropertyOverrides(
											{
												eGTgp2d_M: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion6.div>
						<motion6.div
							className={"framer-1pzjwl4"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"OeHgiH7y3"}
						>
							<motion6.div
								className={"framer-1dhtp9d"}
								data-border={true}
								data-framer-name={"ImageContainer"}
								layoutDependency={layoutDependency}
								layoutId={"rFCwqVUlX"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
							>
								{isDisplayed() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "right",
											positionY: "top",
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											src: "https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?width=2080&height=1600 2080w",
										}}
										className={"framer-3kpdnu"}
										data-framer-appear-id={"3kpdnu"}
										data-framer-name={"Image1"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"Ux8vMwIfk"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed1() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "left",
											positionY: "top",
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											src: "https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?width=2080&height=1600 2080w",
										}}
										className={"framer-1phtgyj"}
										data-framer-appear-id={"1phtgyj"}
										data-framer-name={"Image2"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"eDCSg8gSl"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed2() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "left",
											positionY: "top",
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											src: "https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?width=2080&height=1600 2080w",
										}}
										className={"framer-l7exuc"}
										data-framer-appear-id={"l7exuc"}
										data-framer-name={"Image3"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"dKVXIlpbk"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed3() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "left",
											positionY: "top",
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											src: "https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?width=2080&height=1600 2080w",
										}}
										className={"framer-10pl46h"}
										data-framer-appear-id={"10pl46h"}
										data-framer-name={"Image4"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"zotwu8w59"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed4() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "left",
											positionY: "top",
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											src: "https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?width=2080&height=1600 2080w",
										}}
										className={"framer-b3cq3q"}
										data-framer-appear-id={"b3cq3q"}
										data-framer-name={"Image5"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"ECY6XYcrY"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
							</motion6.div>
							<motion6.div
								className={"framer-df2tak"}
								data-framer-name={"Texts"}
								layoutDependency={layoutDependency}
								layoutId={"mOukN_8Fs"}
							>
								{isDisplayed() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-18zejox"}
										data-framer-appear-id={"18zejox"}
										data-framer-name={"Text1"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"XbZ9fHPt3"}
										optimized={true}
									>
										<motion6.div
											className={"framer-5hw9s0"}
											layoutDependency={layoutDependency}
											layoutId={"CXzSl71QG"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-fneck"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"TdOTRU64O"}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														zmBSKyFdr: {
															effect: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React6.Fragment>
													<motion6.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Smart Task Prioritization"}
													</motion6.h3>
												</React6.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1me5nn6"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"VN5d3HKfI"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence analyzes your deadlines, goals, and habits to suggest what matters most \u2014 right now."
														}
													</motion6.p>
												</React6.Fragment>
											</RichText>
										</motion6.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-w1iqr3-container"}
												layoutDependency={layoutDependency}
												layoutId={"VVR8V22sU-container"}
												nodeId={"VVR8V22sU"}
												rendersWithMotion={true}
												scopeId={"NmtswHhYq"}
											>
												{_jsx6(stdin_default7, {
													H9fdquxmO: "Start prioritizing now",
													height: "100%",
													id: "VVR8V22sU",
													layoutId: "VVR8V22sU",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
													WqF2Pzc7v: "template-remixed",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed1() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-oo5mog"}
										data-framer-appear-id={"oo5mog"}
										data-framer-name={"Text2"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"ygrr28WNX"}
										optimized={true}
									>
										<motion6.div
											className={"framer-bdsx2f"}
											layoutDependency={layoutDependency}
											layoutId={"RtUS2okSQ"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1eykkrp"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"WWBXGVatk"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Focus Mode"}
													</motion6.h3>
												</React6.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-cutel3"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"oZ7Eb9adr"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence reduces interruptions and triggers friendly reminders to gently bring you back on track."
														}
													</motion6.p>
												</React6.Fragment>
											</RichText>
										</motion6.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-3my1d5-container"}
												layoutDependency={layoutDependency}
												layoutId={"ZnZTVmii5-container"}
												nodeId={"ZnZTVmii5"}
												rendersWithMotion={true}
												scopeId={"NmtswHhYq"}
											>
												{_jsx6(stdin_default7, {
													H9fdquxmO: "Enter focus mode",
													height: "100%",
													id: "ZnZTVmii5",
													layoutId: "ZnZTVmii5",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
													WqF2Pzc7v: "template-remixed",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed2() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1oov6hq"}
										data-framer-appear-id={"1oov6hq"}
										data-framer-name={"Text3"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"vF0tti_ii"}
										optimized={true}
									>
										<motion6.div
											className={"framer-1stpzz6"}
											layoutDependency={layoutDependency}
											layoutId={"X2d5lcNTq"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-zzrfoi"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"IpuccyS9a"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Minimal Planner"}
													</motion6.h3>
												</React6.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-13upcro"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"tAlAc_7zR"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence gives you a minimalist interface that helps you plan your day in seconds, without the stress."
														}
													</motion6.p>
												</React6.Fragment>
											</RichText>
										</motion6.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-e6697q-container"}
												layoutDependency={layoutDependency}
												layoutId={"e0SPzBE4W-container"}
												nodeId={"e0SPzBE4W"}
												rendersWithMotion={true}
												scopeId={"NmtswHhYq"}
											>
												{_jsx6(stdin_default7, {
													H9fdquxmO: "Plan your week",
													height: "100%",
													id: "e0SPzBE4W",
													layoutId: "e0SPzBE4W",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
													WqF2Pzc7v: "template-remixed",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed3() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-lhnxb"}
										data-framer-appear-id={"lhnxb"}
										data-framer-name={"Text4"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"a4I87KcjT"}
										optimized={true}
									>
										<motion6.div
											className={"framer-1o61as8"}
											layoutDependency={layoutDependency}
											layoutId={"yzmhJCIPI"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-13envlc"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Sv5zYNZ5g"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Unified Workspace"}
													</motion6.h3>
												</React6.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-5k1qit"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"skvtI502x"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence brings it all together \u2014 in one intuitive place."
														}
													</motion6.p>
												</React6.Fragment>
											</RichText>
										</motion6.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-f8gsx3-container"}
												layoutDependency={layoutDependency}
												layoutId={"gr02_vYHk-container"}
												nodeId={"gr02_vYHk"}
												rendersWithMotion={true}
												scopeId={"NmtswHhYq"}
											>
												{_jsx6(stdin_default7, {
													H9fdquxmO: "Get organized",
													height: "100%",
													id: "gr02_vYHk",
													layoutId: "gr02_vYHk",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
													WqF2Pzc7v: "template-remixed",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed4() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-2etaxe"}
										data-framer-appear-id={"2etaxe"}
										data-framer-name={"Text5"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"oSxGllFnL"}
										optimized={true}
									>
										<motion6.div
											className={"framer-1qife5q"}
											layoutDependency={layoutDependency}
											layoutId={"UfbSskzK8"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-3b02sn"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"wRwrsfKaV"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Progress Tracking"}
													</motion6.h3>
												</React6.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1xphfj6"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"VX1Dlt4jy"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React6.Fragment>
													<motion6.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence helps you reflect on your accomplishments and measure real progress."
														}
													</motion6.p>
												</React6.Fragment>
											</RichText>
										</motion6.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-xv1mh8-container"}
												layoutDependency={layoutDependency}
												layoutId={"s_JlDNEFw-container"}
												nodeId={"s_JlDNEFw"}
												rendersWithMotion={true}
												scopeId={"NmtswHhYq"}
											>
												{_jsx6(stdin_default7, {
													H9fdquxmO: "Track progress",
													height: "100%",
													id: "s_JlDNEFw",
													layoutId: "s_JlDNEFw",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
													WqF2Pzc7v: "template-remixed",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
							</motion6.div>
						</motion6.div>
					</motion6.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Guqct.framer-j7rzw4, .framer-Guqct .framer-j7rzw4 { display: block; }",
	".framer-Guqct.framer-2okwsd { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1080px; }",
	".framer-Guqct .framer-1ifcwlt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Guqct .framer-ga0jyi-container, .framer-Guqct .framer-1p0tjdf-container, .framer-Guqct .framer-1rsa34-container, .framer-Guqct .framer-ysc0b2-container, .framer-Guqct .framer-n8zyxg-container, .framer-Guqct .framer-w1iqr3-container, .framer-Guqct .framer-3my1d5-container, .framer-Guqct .framer-e6697q-container, .framer-Guqct .framer-f8gsx3-container, .framer-Guqct .framer-xv1mh8-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Guqct .framer-1pzjwl4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Guqct .framer-1dhtp9d { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Guqct .framer-3kpdnu, .framer-Guqct .framer-1phtgyj, .framer-Guqct .framer-l7exuc, .framer-Guqct .framer-10pl46h, .framer-Guqct .framer-b3cq3q { flex: none; height: 400px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Guqct .framer-df2tak { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Guqct .framer-18zejox, .framer-Guqct .framer-oo5mog, .framer-Guqct .framer-1oov6hq, .framer-Guqct .framer-lhnxb, .framer-Guqct .framer-2etaxe { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 1px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Guqct .framer-5hw9s0, .framer-Guqct .framer-bdsx2f, .framer-Guqct .framer-1stpzz6, .framer-Guqct .framer-1o61as8, .framer-Guqct .framer-1qife5q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Guqct .framer-fneck, .framer-Guqct .framer-1eykkrp, .framer-Guqct .framer-zzrfoi, .framer-Guqct .framer-13envlc, .framer-Guqct .framer-3b02sn { -webkit-user-select: none; flex: none; height: auto; pointer-events: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Guqct .framer-1me5nn6, .framer-Guqct .framer-cutel3, .framer-Guqct .framer-13upcro, .framer-Guqct .framer-5k1qit, .framer-Guqct .framer-1xphfj6 { --framer-text-wrap-override: balance; -webkit-user-select: none; flex: none; height: auto; pointer-events: auto; position: relative; user-select: none; width: 100%; }",
	...css2,
	...css,
	'.framer-Guqct[data-border="true"]::after, .framer-Guqct [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerNmtswHhYq = withCSS6(Component6, css8, "framer-Guqct");
var stdin_default13 = FramerNmtswHhYq;
FramerNmtswHhYq.displayName = "Features (Desktop)";
FramerNmtswHhYq.defaultProps = {
	height: 2060,
	width: 1080,
};
addPropertyControls6(FramerNmtswHhYq, {
	variant: {
		options: [
			"xVfgwnkh3",
			"zmBSKyFdr",
			"qU7hT9U2_",
			"TPHAAZT5B",
			"khS0PpTZ5",
			"eGTgp2d_M",
		],
		optionTitles: [
			"Main (Change this)",
			"Task Prioritization",
			"Focus Mode",
			"Minimal Planner",
			"Unified Workspace",
			"Progress Tracking",
		],
		title: "Variant",
		type: ControlType6.Enum,
	},
});
addFonts(
	FramerNmtswHhYq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ChipFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerNmtswHhYq.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default6, {}, context),
			forwardLoader(stdin_default7, {}, context),
		]);
	},
};

// virtual:features-desktop
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "zmBSKyFdr",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default13, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturesDesktopFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default13}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default13);
var features_desktop_default = ComponentWithRoot;
export { features_desktop_default as default };
