// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Main (Change this)' | 'Task Prioritization' | 'Focus Mode' | 'Minimal Planner' | 'Unified Workspace' | 'Progress Tracking' // Variant
}} Props

 */
import {
	stdin_default,
	stdin_default2,
	stdin_default3,
	stdin_default4,
	stdin_default5,
	stdin_default6,
} from "./chunks/chunk-IYJX6KNH.js";
import "./chunks/chunk-BDE5Q2MY.js";
import { className, css, fonts } from "./chunks/chunk-2HMR454I.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WOTVKQ2B.js";
import { stdin_default as stdin_default7 } from "./chunks/chunk-XMJR4DGB.js";
import "./chunks/chunk-K3KYO637.js";
import "./chunks/chunk-NTQNEBCY.js";
import "./chunks/chunk-URGOVI2W.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:features-mobile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/brohebSqpo7B0wfoBxOh/VCyhde2pIdazr67uqnuW/W8ogrNrEy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ChipFonts = getFonts(stdin_default6);
var Image1WithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image1),
);
var ButtonFonts = getFonts(stdin_default7);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = [
	"CrtTkYWkp",
	"ahuhzRdiL",
	"wZQhkma3L",
	"FXnveiDkG",
	"f4yzW9VIF",
	"APmw6rYBU",
];
var serializationHash = "framer-Cy2oM";
var variantClassNames = {
	ahuhzRdiL: "framer-v-1185v65",
	APmw6rYBU: "framer-v-4jblyt",
	CrtTkYWkp: "framer-v-162j0ku",
	f4yzW9VIF: "framer-v-1xo61al",
	FXnveiDkG: "framer-v-170gqdb",
	wZQhkma3L: "framer-v-z621f7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.12, 0.23, 0.17, 0.99],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var animation2 = {
	filter: "blur(4px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 12,
};
var transition3 = {
	delay: 0.05,
	duration: 0.8,
	ease: [0.12, 0.23, 0.17, 0.98],
	type: "tween",
};
var textEffect = {
	effect: animation2,
	repeat: false,
	startDelay: 0,
	threshold: 0.5,
	tokenization: "line",
	transition: transition3,
	trigger: "onInView",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Focus Mode": "wZQhkma3L",
	"Main (Change this)": "CrtTkYWkp",
	"Minimal Planner": "FXnveiDkG",
	"Progress Tracking": "APmw6rYBU",
	"Task Prioritization": "ahuhzRdiL",
	"Unified Workspace": "f4yzW9VIF",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CrtTkYWkp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CrtTkYWkp",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const tSHGITUhm1nobd0y = activeVariantCallback(async (...args) => {
		setVariant("ahuhzRdiL");
	});
	const tSHGITUhm1dertwd = activeVariantCallback(async (...args) => {
		setVariant("wZQhkma3L");
	});
	const tSHGITUhm10co2dq = activeVariantCallback(async (...args) => {
		setVariant("FXnveiDkG");
	});
	const tSHGITUhm1k65t94 = activeVariantCallback(async (...args) => {
		setVariant("f4yzW9VIF");
	});
	const tSHGITUhmw3myxm = activeVariantCallback(async (...args) => {
		setVariant("APmw6rYBU");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["wZQhkma3L", "FXnveiDkG", "f4yzW9VIF", "APmw6rYBU"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (
			["ahuhzRdiL", "FXnveiDkG", "f4yzW9VIF", "APmw6rYBU"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (
			["ahuhzRdiL", "wZQhkma3L", "f4yzW9VIF", "APmw6rYBU"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (
			["ahuhzRdiL", "wZQhkma3L", "FXnveiDkG", "APmw6rYBU"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed4 = () => {
		if (
			["ahuhzRdiL", "wZQhkma3L", "FXnveiDkG", "f4yzW9VIF"].includes(baseVariant)
		)
			return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-162j0ku",
							className3,
							classNames,
						)}
						data-framer-name={"Main (Change this)"}
						layoutDependency={layoutDependency}
						layoutId={"CrtTkYWkp"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ahuhzRdiL: {
									"data-framer-name": "Task Prioritization",
								},
								APmw6rYBU: {
									"data-framer-name": "Progress Tracking",
								},
								f4yzW9VIF: {
									"data-framer-name": "Unified Workspace",
								},
								FXnveiDkG: {
									"data-framer-name": "Minimal Planner",
								},
								wZQhkma3L: {
									"data-framer-name": "Focus Mode",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1k0d138"}
							data-framer-name={"ChipsList"}
							data-hide-scrollbars={true}
							layoutDependency={layoutDependency}
							layoutId={"c48XuoMsZ"}
						>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-n7u5ch-container"}
									layoutDependency={layoutDependency}
									layoutId={"PbCpwMOjI-container"}
									nodeId={"PbCpwMOjI"}
									rendersWithMotion={true}
									scopeId={"W8ogrNrEy"}
								>
									{_jsx(stdin_default6, {
										height: "100%",
										id: "PbCpwMOjI",
										layoutId: "PbCpwMOjI",
										QYzJ5sW1W: stdin_default,
										tSHGITUhm: tSHGITUhm1nobd0y,
										variant: matchVariant("zIyvfaguP"),
										width: "100%",
										yxGK5lOXT: "Task Prioritization",
										...addPropertyOverrides(
											{
												APmw6rYBU: {
													variant: matchVariant("fFWaboF5d"),
												},
												f4yzW9VIF: {
													variant: matchVariant("fFWaboF5d"),
												},
												FXnveiDkG: {
													variant: matchVariant("fFWaboF5d"),
												},
												wZQhkma3L: {
													variant: matchVariant("fFWaboF5d"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-r85egq-container"}
									layoutDependency={layoutDependency}
									layoutId={"fbSJpnx1i-container"}
									nodeId={"fbSJpnx1i"}
									rendersWithMotion={true}
									scopeId={"W8ogrNrEy"}
								>
									{_jsx(stdin_default6, {
										height: "100%",
										id: "fbSJpnx1i",
										layoutId: "fbSJpnx1i",
										QYzJ5sW1W: stdin_default3,
										tSHGITUhm: tSHGITUhm1dertwd,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yxGK5lOXT: "Focus Mode",
										...addPropertyOverrides(
											{
												wZQhkma3L: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-qzx5no-container"}
									layoutDependency={layoutDependency}
									layoutId={"uYCV01mHB-container"}
									nodeId={"uYCV01mHB"}
									rendersWithMotion={true}
									scopeId={"W8ogrNrEy"}
								>
									{_jsx(stdin_default6, {
										height: "100%",
										id: "uYCV01mHB",
										layoutId: "uYCV01mHB",
										QYzJ5sW1W: stdin_default4,
										tSHGITUhm: tSHGITUhm10co2dq,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yxGK5lOXT: "Minimal Planner",
										...addPropertyOverrides(
											{
												FXnveiDkG: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-1tvgyui-container"}
									layoutDependency={layoutDependency}
									layoutId={"PhmRl_G2Q-container"}
									nodeId={"PhmRl_G2Q"}
									rendersWithMotion={true}
									scopeId={"W8ogrNrEy"}
								>
									{_jsx(stdin_default6, {
										height: "100%",
										id: "PhmRl_G2Q",
										layoutId: "PhmRl_G2Q",
										QYzJ5sW1W: stdin_default5,
										tSHGITUhm: tSHGITUhm1k65t94,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yxGK5lOXT: "Unified Workspace",
										...addPropertyOverrides(
											{
												f4yzW9VIF: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider height={36}>
								<SmartComponentScopedContainer
									className={"framer-180j21p-container"}
									layoutDependency={layoutDependency}
									layoutId={"Ip822x_vQ-container"}
									nodeId={"Ip822x_vQ"}
									rendersWithMotion={true}
									scopeId={"W8ogrNrEy"}
								>
									{_jsx(stdin_default6, {
										height: "100%",
										id: "Ip822x_vQ",
										layoutId: "Ip822x_vQ",
										QYzJ5sW1W: stdin_default2,
										tSHGITUhm: tSHGITUhmw3myxm,
										variant: matchVariant("fFWaboF5d"),
										width: "100%",
										yxGK5lOXT: "Progress Tracking",
										...addPropertyOverrides(
											{
												APmw6rYBU: {
													variant: matchVariant("zIyvfaguP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-10ojw5i"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"C8gmEyHDp"}
						>
							<motion.div
								className={"framer-q6ssto"}
								data-border={true}
								data-framer-name={"ImageContainer"}
								layoutDependency={layoutDependency}
								layoutId={"IYrjM5xqb"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
							>
								{isDisplayed() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "right",
											positionY: "top",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/MRfxoi6b3x5LAQs36zE406ggD8.png?width=2080&height=1600 2080w",
										}}
										className={"framer-1ob6wl3"}
										data-framer-appear-id={"1ob6wl3"}
										data-framer-name={"Image1"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"RLJa2lG4L"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed1() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/akrKqm0uxmAyeHpsQQsh5wLyXTc.png?width=2080&height=1600 2080w",
										}}
										className={"framer-8a4thm"}
										data-framer-appear-id={"8a4thm"}
										data-framer-name={"Image2"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"WF5BAUThQ"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed2() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/iG8DgZ5yZ6DIluRaqKXS0SiRKE.png?width=2080&height=1600 2080w",
										}}
										className={"framer-ii9j9q"}
										data-framer-appear-id={"ii9j9q"}
										data-framer-name={"Image3"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"ruYhaMtfX"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed3() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/UZxqknYPw7WF31Qpckatfykpw.png?width=2080&height=1600 2080w",
										}}
										className={"framer-jizjwz"}
										data-framer-appear-id={"jizjwz"}
										data-framer-name={"Image4"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"HW2Jk0m9l"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
								{isDisplayed4() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 1600,
											pixelWidth: 2080,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?width=2080&height=1600",
											srcSet:
												"https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=512&width=2080&height=1600 512w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=1024&width=2080&height=1600 1024w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?scale-down-to=2048&width=2080&height=1600 2048w,https://framerusercontent.com/images/hBbkI6p5uxDhrLSm3gSggLjmCQc.png?width=2080&height=1600 2080w",
										}}
										className={"framer-1i2lmm6"}
										data-framer-appear-id={"1i2lmm6"}
										data-framer-name={"Image5"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"uPHlZ3J0q"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										}}
									/>
								)}
							</motion.div>
							<motion.div
								className={"framer-e2z7w0"}
								data-framer-name={"Texts"}
								layoutDependency={layoutDependency}
								layoutId={"Vk3SFARLe"}
							>
								{isDisplayed() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-b19vsh"}
										data-framer-appear-id={"b19vsh"}
										data-framer-name={"Text1"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"OqgsHxWp2"}
										optimized={true}
									>
										<motion.div
											className={"framer-zxzhtt"}
											layoutDependency={layoutDependency}
											layoutId={"B1tCrEYzE"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-qmc136"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Vp0xypmmP"}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														ahuhzRdiL: {
															effect: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Smart Task Prioritization"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-mv837r"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"qyW8CU8W2"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence analyzes your deadlines, goals, and habits to suggest what matters most \u2014 right now."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-ce0pse-container"}
												layoutDependency={layoutDependency}
												layoutId={"TexICTfHs-container"}
												nodeId={"TexICTfHs"}
												rendersWithMotion={true}
												scopeId={"W8ogrNrEy"}
											>
												{_jsx(stdin_default7, {
													H9fdquxmO: "Start prioritizing now",
													height: "100%",
													id: "TexICTfHs",
													layoutId: "TexICTfHs",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													style: {
														height: "100%",
													},
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed1() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-2wchds"}
										data-framer-appear-id={"2wchds"}
										data-framer-name={"Text2"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"RPnwNbcJ9"}
										optimized={true}
									>
										<motion.div
											className={"framer-gseea9"}
											layoutDependency={layoutDependency}
											layoutId={"SwPztQn4d"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-8tdfp3"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"DvUzQOzrl"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Focus Mode"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-912fwx"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"BRWh34PbZ"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence reduces interruptions and triggers friendly reminders to gently bring you back on track."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-t5c69s-container"}
												layoutDependency={layoutDependency}
												layoutId={"hhmHCV9AM-container"}
												nodeId={"hhmHCV9AM"}
												rendersWithMotion={true}
												scopeId={"W8ogrNrEy"}
											>
												{_jsx(stdin_default7, {
													H9fdquxmO: "Enter focus mode",
													height: "100%",
													id: "hhmHCV9AM",
													layoutId: "hhmHCV9AM",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													style: {
														height: "100%",
													},
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed2() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1l9it8e"}
										data-framer-appear-id={"1l9it8e"}
										data-framer-name={"Text3"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"fCVlCJMD_"}
										optimized={true}
									>
										<motion.div
											className={"framer-t8tlyg"}
											layoutDependency={layoutDependency}
											layoutId={"RQMHuX1KL"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-qh4fbw"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"lGhqmhtu5"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Minimal Planner"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1r96j5y"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"mURSTNtPg"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence gives you a minimalist interface that helps you plan your day in seconds, without the stress."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-1rv8q7s-container"}
												layoutDependency={layoutDependency}
												layoutId={"VEUODRRYM-container"}
												nodeId={"VEUODRRYM"}
												rendersWithMotion={true}
												scopeId={"W8ogrNrEy"}
											>
												{_jsx(stdin_default7, {
													H9fdquxmO: "Plan your week",
													height: "100%",
													id: "VEUODRRYM",
													layoutId: "VEUODRRYM",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													style: {
														height: "100%",
													},
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed3() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-x4jvwh"}
										data-framer-appear-id={"x4jvwh"}
										data-framer-name={"Text4"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"jmN44LIZ_"}
										optimized={true}
									>
										<motion.div
											className={"framer-jbo7zo"}
											layoutDependency={layoutDependency}
											layoutId={"esNZjz4aI"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-j79pfm"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Rtw6U_fja"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Unified Workspace"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1qmycyr"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"O50TY9w81"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence brings it all together \u2014 in one intuitive place."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-1q29vxf-container"}
												layoutDependency={layoutDependency}
												layoutId={"oSYg2bWhf-container"}
												nodeId={"oSYg2bWhf"}
												rendersWithMotion={true}
												scopeId={"W8ogrNrEy"}
											>
												{_jsx(stdin_default7, {
													H9fdquxmO: "Get organized",
													height: "100%",
													id: "oSYg2bWhf",
													layoutId: "oSYg2bWhf",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													style: {
														height: "100%",
													},
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{isDisplayed4() && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-14fyng1"}
										data-framer-appear-id={"14fyng1"}
										data-framer-name={"Text5"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"RPuhdteGN"}
										optimized={true}
									>
										<motion.div
											className={"framer-nuszxb"}
											layoutDependency={layoutDependency}
											layoutId={"ZeaUXQpnm"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-ymhro"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"cM17F1R2T"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-15f9wtz"}
														data-styles-preset={"PRbE5oqPp"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Progress Tracking"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1n4y27l"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"q45EiPeME"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Cadence helps you reflect on your accomplishments and measure real progress."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider height={48}>
											<SmartComponentScopedContainer
												className={"framer-a99u04-container"}
												layoutDependency={layoutDependency}
												layoutId={"bIPAjWTSn-container"}
												nodeId={"bIPAjWTSn"}
												rendersWithMotion={true}
												scopeId={"W8ogrNrEy"}
											>
												{_jsx(stdin_default7, {
													H9fdquxmO: "Track progress",
													height: "100%",
													id: "bIPAjWTSn",
													layoutId: "bIPAjWTSn",
													qa2d0SHwc: "https://framer.link/sbOJsNi",
													qZfHbmzQf: false,
													style: {
														height: "100%",
													},
													uFNDrhDvW: true,
													variant: matchVariant("Y1ageSf63"),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Cy2oM.framer-14r3fkb, .framer-Cy2oM .framer-14r3fkb { display: block; }",
	".framer-Cy2oM.framer-162j0ku { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 360px; }",
	".framer-Cy2oM .framer-1k0d138 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; overflow-x: auto; padding: 0px; position: relative; width: 100%; }",
	".framer-Cy2oM .framer-n7u5ch-container, .framer-Cy2oM .framer-r85egq-container, .framer-Cy2oM .framer-qzx5no-container, .framer-Cy2oM .framer-1tvgyui-container, .framer-Cy2oM .framer-180j21p-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Cy2oM .framer-10ojw5i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Cy2oM .framer-q6ssto { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Cy2oM .framer-1ob6wl3, .framer-Cy2oM .framer-8a4thm, .framer-Cy2oM .framer-ii9j9q, .framer-Cy2oM .framer-jizjwz, .framer-Cy2oM .framer-1i2lmm6 { flex: none; height: 277px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Cy2oM .framer-e2z7w0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Cy2oM .framer-b19vsh, .framer-Cy2oM .framer-2wchds, .framer-Cy2oM .framer-1l9it8e, .framer-Cy2oM .framer-x4jvwh, .framer-Cy2oM .framer-14fyng1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Cy2oM .framer-zxzhtt, .framer-Cy2oM .framer-gseea9, .framer-Cy2oM .framer-t8tlyg, .framer-Cy2oM .framer-jbo7zo, .framer-Cy2oM .framer-nuszxb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Cy2oM .framer-qmc136, .framer-Cy2oM .framer-mv837r, .framer-Cy2oM .framer-8tdfp3, .framer-Cy2oM .framer-912fwx, .framer-Cy2oM .framer-qh4fbw, .framer-Cy2oM .framer-1r96j5y, .framer-Cy2oM .framer-j79pfm, .framer-Cy2oM .framer-1qmycyr, .framer-Cy2oM .framer-ymhro, .framer-Cy2oM .framer-1n4y27l { -webkit-user-select: none; flex: none; height: auto; pointer-events: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Cy2oM .framer-ce0pse-container, .framer-Cy2oM .framer-t5c69s-container, .framer-Cy2oM .framer-1rv8q7s-container, .framer-Cy2oM .framer-1q29vxf-container, .framer-Cy2oM .framer-a99u04-container { flex: none; height: 48px; position: relative; width: auto; }",
	...css2,
	...css,
	'.framer-Cy2oM[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-Cy2oM [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
	'.framer-Cy2oM[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-Cy2oM [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
	'.framer-Cy2oM[data-hide-scrollbars="true"], .framer-Cy2oM [data-hide-scrollbars="true"] { scrollbar-width: none; }',
	'.framer-Cy2oM[data-border="true"]::after, .framer-Cy2oM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerW8ogrNrEy = withCSS(Component, css3, "framer-Cy2oM");
var stdin_default8 = FramerW8ogrNrEy;
FramerW8ogrNrEy.displayName = "Features (Mobile)";
FramerW8ogrNrEy.defaultProps = {
	height: 2455,
	width: 360,
};
addPropertyControls(FramerW8ogrNrEy, {
	variant: {
		options: [
			"CrtTkYWkp",
			"ahuhzRdiL",
			"wZQhkma3L",
			"FXnveiDkG",
			"f4yzW9VIF",
			"APmw6rYBU",
		],
		optionTitles: [
			"Main (Change this)",
			"Task Prioritization",
			"Focus Mode",
			"Minimal Planner",
			"Unified Workspace",
			"Progress Tracking",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerW8ogrNrEy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ChipFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerW8ogrNrEy.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default6, {}, context),
			forwardLoader(stdin_default7, {}, context),
		]);
	},
};

// virtual:features-mobile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ahuhzRdiL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default8, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturesMobileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default8}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default8);
var features_mobile_default = ComponentWithRoot;
export { features_mobile_default as default };
