// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-KXAZNTJD.js";
import { className, css, fonts } from "./chunks/chunk-FJRSPKHF.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-NTQNEBCY.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-NJFOTUSO.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-URGOVI2W.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zsVGIb7vZRyskGVYQzV5/3YLjWfPWInilEqDCrkbP/U2H1YDylB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SpeedometerFonts = getFonts(stdin_default);
var cycleOrder = ["U7d2JLtMr", "AstvX0xjI", "sYtUHpt63"];
var serializationHash = "framer-efft2";
var variantClassNames = {
	AstvX0xjI: "framer-v-19yqtw7",
	sYtUHpt63: "framer-v-1h0y46p",
	U7d2JLtMr: "framer-v-ro6ncg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "U7d2JLtMr",
	Mobile: "sYtUHpt63",
	Tablet: "AstvX0xjI",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "U7d2JLtMr",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "U7d2JLtMr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className4, className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ro6ncg",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"U7d2JLtMr"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								AstvX0xjI: {
									"data-framer-name": "Tablet",
								},
								sYtUHpt63: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-qszimg"}
							layoutDependency={layoutDependency}
							layoutId={"jOyG1U3GO"}
						>
							<motion.div
								className={"framer-cjjx5k"}
								data-framer-name={"LeftContent"}
								layoutDependency={layoutDependency}
								layoutId={"Inx6dWMvC"}
							>
								<motion.div
									className={"framer-8g96ib"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"N0F1m1NfD"}
								>
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"iESIZOZJF"}
										scopeId={"U2H1YDylB"}
									>
										<motion.a
											className={"framer-zant0z framer-1uki5w6"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"iESIZOZJF"}
										>
											<motion.div
												className={"framer-1d9jfjx"}
												data-border={true}
												layoutDependency={layoutDependency}
												layoutId={"LAkGeOyS8"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color":
														"var(--token-393017ca-624a-4c0e-8abf-e25581b76ff1, rgba(0, 0, 0, 0.1))",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													backgroundColor:
														"var(--token-da609428-544a-4043-ad9a-562a44448ad4, rgb(255, 255, 255))",
													borderBottomLeftRadius: 4,
													borderBottomRightRadius: 4,
													borderTopLeftRadius: 4,
													borderTopRightRadius: 4,
												}}
											>
												{_jsx(stdin_default, {
													animated: true,
													className: "framer-15qr6t8",
													layoutDependency,
													layoutId: "SbbAwqrqR",
													style: {
														"--1m6trwb": 0,
														"--21h8s6": "rgb(0, 0, 0)",
														"--pgex8v": 1.5,
													},
												})}
											</motion.div>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1ki233a"}
												data-framer-name={"Spaces"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"FIrzfj1ld"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-o5z0st"}
														data-styles-preset={"IsDMY7Ceo"}
														dir={"auto"}
													>
														{"Cadence"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.a>
									</Link>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1avtui5"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"n1XEC922r"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-2io64c"}
												data-styles-preset={"AnqNoZ_U2"}
												dir={"auto"}
											>
												{
													"Your AI-powered companion for effortless productivity."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-14klf9d"}
									layoutDependency={layoutDependency}
									layoutId={"U2PmrIeS0"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-itu9sf"}
										data-framer-name={"Created By"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"upgy6LCHf"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-2io64c"}
												data-styles-preset={"AnqNoZ_U2"}
												dir={"auto"}
											>
												{"Created by"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-198uyml"}
										data-framer-name={"Arthur"}
										layoutDependency={layoutDependency}
										layoutId={"x9TBlV3TV"}
									>
										<Image1
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(48 +
															((componentViewport?.height || 328) - 96 - 669) /
																2) +
														0 +
														0 +
														645 +
														0 +
														0,
												),
												pixelHeight: 1024,
												pixelWidth: 1024,
												sizes: "24px",
												src: "https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?width=1024&height=1024",
												srcSet:
													"https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?width=1024&height=1024 1024w",
											}}
											className={"framer-18unbye"}
											data-framer-name={"Pic"}
											layoutDependency={layoutDependency}
											layoutId={"XPEr8jCKh"}
											style={{
												borderBottomLeftRadius: 50,
												borderBottomRightRadius: 50,
												borderTopLeftRadius: 50,
												borderTopRightRadius: 50,
											}}
											{...addPropertyOverrides(
												{
													sYtUHpt63: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	24 +
																	0 +
																	0 +
																	717 +
																	0 +
																	153 +
																	0 +
																	0,
															),
															pixelHeight: 1024,
															pixelWidth: 1024,
															sizes: "24px",
															src: "https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?width=1024&height=1024",
															srcSet:
																"https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/ONjFjJOjmJKUkxsVtaYneUJVcnM.jpg?width=1024&height=1024 1024w",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-10w3mkh"}
											data-framer-name={"Created By"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ny5Ikeljv"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-z5yjcz"}
													data-styles-preset={"I1dFaNZDG"}
													dir={"auto"}
												>
													<Link
														href={"https://x.com/uxui_arthur"}
														motionChild={true}
														nodeId={"ny5Ikeljv"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Arthur"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-4fmeaq"}
										data-framer-name={"Created By"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Pfni2o4kH"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-2io64c"}
												data-styles-preset={"AnqNoZ_U2"}
												dir={"auto"}
											>
												{"in"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1o378ac"}
										data-framer-name={"Created By"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"b7SyWhaTY"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-z5yjcz"}
												data-styles-preset={"I1dFaNZDG"}
												dir={"auto"}
											>
												<Link
													href={"https://framer.link/arthurdch"}
													motionChild={true}
													nodeId={"b7SyWhaTY"}
													openInNewTab={true}
													relValues={[]}
													scopeId={"U2H1YDylB"}
													smoothScroll={false}
												>
													<motion.a
														className={"framer-styles-preset-161xcm"}
														data-styles-preset={"jbsOSsZpz"}
													>
														{"Framer"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-152cegu"}
								data-framer-name={"RightNavigation"}
								layoutDependency={layoutDependency}
								layoutId={"PL7SbMTbH"}
							>
								<motion.div
									className={"framer-gli914"}
									data-framer-name={"Column1"}
									layoutDependency={layoutDependency}
									layoutId={"mvzZey_DX"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-lgxn3h"}
										data-framer-name={"Naviagtion"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"C3HRnfEbR"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-z5yjcz"}
												data-styles-preset={"I1dFaNZDG"}
												dir={"auto"}
											>
												{"Navigation"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-vonj6c"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"xHtx9eGvq"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-jtbtzm"}
											data-framer-name={"FAQ"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"RO_wrv83Q"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":kIdsWxA43",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"RO_wrv83Q"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Features"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-3b0ev8"}
											data-framer-name={"FAQ"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"tHsscTPmZ"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":tuwYFvqCK",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"tHsscTPmZ"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Benefits"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-ummxzh"}
											data-framer-name={"FAQ"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"BO0cWvGjv"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":w_Xfqog0Q",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"BO0cWvGjv"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Testimonials"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-5tltsz"}
											data-framer-name={"FAQ"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"YRVHce1xc"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":cy05qZSsn",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"YRVHce1xc"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Pricing"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-y5rw3u"}
											data-framer-name={"FAQ"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"BU6X5IRzm"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":EArIols72",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"BU6X5IRzm"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"FAQ"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1537xvy"}
											data-framer-name={"404"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"cSbxYyJbu"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={{
															webPageId: "DDN4tRh_7",
														}}
														motionChild={true}
														nodeId={"cSbxYyJbu"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"404"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-1lr1g7x"}
									data-framer-name={"Socials"}
									layoutDependency={layoutDependency}
									layoutId={"fYBbZXu4v"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-9g8zcl"}
										data-framer-name={"Heading 2 \u2192 Navigation"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"heUuna80k"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-z5yjcz"}
												data-styles-preset={"I1dFaNZDG"}
												dir={"auto"}
											>
												{"Socials"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-4dmj94"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"TLT_m56BU"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1bbb5up"}
											data-framer-name={"Templates"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"mlBUiT0V0"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={"https://x.com/uxui_arthur"}
														motionChild={true}
														nodeId={"mlBUiT0V0"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Twitter (X)"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-dtjk2g"}
											data-framer-name={"Templates"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"esH1UYgtt"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={"https://instagram.com"}
														motionChild={true}
														nodeId={"esH1UYgtt"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Instagram"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-ftlo7o"}
											data-framer-name={"Templates"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"YIJjpWNm7"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-2io64c"}
													data-styles-preset={"AnqNoZ_U2"}
													dir={"auto"}
												>
													<Link
														href={"https://facebook.com"}
														motionChild={true}
														nodeId={"YIJjpWNm7"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"U2H1YDylB"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Facebook"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-efft2.framer-1uki5w6, .framer-efft2 .framer-1uki5w6 { display: block; }",
	".framer-efft2.framer-ro6ncg { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 560px; height: min-content; justify-content: center; overflow: visible; padding: 48px; position: relative; width: 1184px; }",
	".framer-efft2 .framer-qszimg { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1128px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-efft2 .framer-cjjx5k { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: auto; justify-content: space-between; max-width: 320px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-efft2 .framer-8g96ib { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-efft2 .framer-zant0z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-efft2 .framer-1d9jfjx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); }",
	".framer-efft2 .framer-15qr6t8 { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-efft2 .framer-1ki233a { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-efft2 .framer-1avtui5 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-efft2 .framer-14klf9d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-efft2 .framer-itu9sf, .framer-efft2 .framer-10w3mkh, .framer-efft2 .framer-4fmeaq, .framer-efft2 .framer-1o378ac { flex: none; height: 24px; position: relative; white-space: pre; width: auto; }",
	".framer-efft2 .framer-198uyml { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-efft2 .framer-18unbye { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-efft2 .framer-152cegu { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; max-width: 320px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-efft2 .framer-gli914, .framer-efft2 .framer-1lr1g7x { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-efft2 .framer-lgxn3h, .framer-efft2 .framer-9g8zcl { flex: none; height: 27px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-efft2 .framer-vonj6c, .framer-efft2 .framer-4dmj94 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-efft2 .framer-jtbtzm, .framer-efft2 .framer-3b0ev8, .framer-efft2 .framer-ummxzh, .framer-efft2 .framer-5tltsz, .framer-efft2 .framer-y5rw3u, .framer-efft2 .framer-1537xvy, .framer-efft2 .framer-1bbb5up, .framer-efft2 .framer-dtjk2g, .framer-efft2 .framer-ftlo7o { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-efft2.framer-v-19yqtw7 .framer-152cegu { gap: 32px; }",
	".framer-efft2.framer-v-1h0y46p.framer-ro6ncg { flex-direction: column; gap: 48px; justify-content: flex-start; padding: 24px; width: 390px; }",
	".framer-efft2.framer-v-1h0y46p .framer-qszimg { flex: none; flex-direction: column; gap: 48px; justify-content: flex-start; width: 100%; }",
	".framer-efft2.framer-v-1h0y46p .framer-cjjx5k { align-self: unset; flex: none; gap: 24px; height: min-content; justify-content: flex-start; order: 1; width: 100%; }",
	".framer-efft2.framer-v-1h0y46p .framer-152cegu { flex: none; order: 0; width: 100%; }",
	...css4,
	...css2,
	...css3,
	...css,
	'.framer-efft2[data-border="true"]::after, .framer-efft2 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerU2H1YDylB = withCSS(Component, css5, "framer-efft2");
var stdin_default2 = FramerU2H1YDylB;
FramerU2H1YDylB.displayName = "Footer";
FramerU2H1YDylB.defaultProps = {
	height: 328,
	width: 1184,
};
addPropertyControls(FramerU2H1YDylB, {
	variant: {
		options: ["U7d2JLtMr", "AstvX0xjI", "sYtUHpt63"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerU2H1YDylB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SpeedometerFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sYtUHpt63",
	md: "AstvX0xjI",
	xl: "U7d2JLtMr",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
