// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * closeOverlay?: Function // Close Overlay
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-FJRSPKHF.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:mobile-menu
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/p8h1P0jEF0xMZri8oKaj/OFOgOICurqHviUGFPwk1/DmdlwUBKp.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/s9ICNln7If6dbx787s8J/bsSFrd6i3uQgWvg7HD50/gpufTpA3b.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 12 0 L 0 12" fill="transparent" height="12px" id="qMvRy61Gj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(6 6)" width="12px"/><path d="M 0 0 L 12 12" fill="transparent" height="12px" id="YX0AMSC6b" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(6 6)" width="12px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2710857035", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-RiU4T", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css2 = [
	`.framer-RiU4T { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-RiU4T");
Icon.displayName = "X";
var stdin_default = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/rk7FoWTJ41zLp0o2rtld/CEfvR77ONUTVASjkbcIT/ByD69Lzay.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;DM Sans-500",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-500italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
				weight: "500",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-7DW32RmYJpso5.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-DRN4d .framer-styles-preset-1eyg8rr:not(.rich-text-wrapper), .framer-DRN4d .framer-styles-preset-1eyg8rr.rich-text-wrapper h2 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-DRN4d .framer-styles-preset-1eyg8rr:not(.rich-text-wrapper), .framer-DRN4d .framer-styles-preset-1eyg8rr.rich-text-wrapper h2 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-DRN4d .framer-styles-preset-1eyg8rr:not(.rich-text-wrapper), .framer-DRN4d .framer-styles-preset-1eyg8rr.rich-text-wrapper h2 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-DRN4d";

// /:https://framerusercontent.com/modules/p8h1P0jEF0xMZri8oKaj/OFOgOICurqHviUGFPwk1/DmdlwUBKp.js
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var XFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.div),
);
var serializationHash = "framer-aN4yM";
var variantClassNames = {
	UtRb_tXfk: "framer-v-gfgffp",
};
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 220,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 716,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition3 = {
	damping: 40,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 160,
};
var transition4 = {
	damping: 40,
	delay: 0.3,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var transition5 = {
	damping: 40,
	delay: 0.4,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var transition6 = {
	damping: 40,
	delay: 0.5,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 0,
};
var transition7 = {
	damping: 40,
	delay: 0.6,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation7 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({ closeOverlay, height, id, width, ...props }) => {
	return {
		...props,
		HYyn6lgsx: closeOverlay ?? props.HYyn6lgsx,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		HYyn6lgsx: HYyn6lgsx2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "UtRb_tXfk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapk75uvl = activeVariantCallback(async (...args) => {
		if (HYyn6lgsx2) {
			const res = await HYyn6lgsx2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFXWithOptimizedAppearEffect
						{...restProps}
						{...gestureHandlers}
						__framer__presenceAnimate={animation}
						__framer__presenceInitial={animation1}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-gfgffp",
							className3,
							classNames,
						)}
						data-framer-appear-id={"gfgffp"}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"UtRb_tXfk"}
						optimized={true}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-5f5e41aa-15b3-439f-89f1-3f142f1cf995, rgb(255, 255, 255))",
							...style,
						}}
					>
						<motion2.div
							className={"framer-11oy1ps"}
							data-framer-name={"Links"}
							layoutDependency={layoutDependency}
							layoutId={"W8a72O4hd"}
						>
							<motion2.div
								className={"framer-4ov5lt"}
								data-framer-name={"Row"}
								layoutDependency={layoutDependency}
								layoutId={"OjsUYy9wL"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation2}
									className={"framer-cj8mrl"}
									data-framer-appear-id={"cj8mrl"}
									data-highlight={true}
									fonts={["Inter"]}
									initial={animation3}
									layoutDependency={layoutDependency}
									layoutId={"VfyGBUxCP"}
									onTap={onTapk75uvl}
									optimized={true}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-1eyg8rr"}
											data-styles-preset={"ByD69Lzay"}
											dir={"auto"}
										>
											<Link
												href={{
													hash: ":kIdsWxA43",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"VfyGBUxCP"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"DmdlwUBKp"}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-161xcm"}
													data-styles-preset={"jbsOSsZpz"}
												>
													{"Features"}
												</motion2.a>
											</Link>
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion2.div>
							<motion2.div
								className={"framer-tlmpk2"}
								data-framer-name={"Row"}
								layoutDependency={layoutDependency}
								layoutId={"Yc5GRdY9y"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation4}
									className={"framer-a1ooox"}
									data-framer-appear-id={"a1ooox"}
									data-highlight={true}
									fonts={["Inter"]}
									initial={animation3}
									layoutDependency={layoutDependency}
									layoutId={"wLY7pLC0Z"}
									onTap={onTapk75uvl}
									optimized={true}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-1eyg8rr"}
											data-styles-preset={"ByD69Lzay"}
											dir={"auto"}
										>
											<Link
												href={{
													hash: ":tuwYFvqCK",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"wLY7pLC0Z"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"DmdlwUBKp"}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-161xcm"}
													data-styles-preset={"jbsOSsZpz"}
												>
													{"Benefits"}
												</motion2.a>
											</Link>
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion2.div>
							<motion2.div
								className={"framer-fmidhh"}
								data-framer-name={"Row"}
								layoutDependency={layoutDependency}
								layoutId={"wzFNodmu2"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation5}
									className={"framer-io8d4x"}
									data-framer-appear-id={"io8d4x"}
									data-highlight={true}
									fonts={["Inter"]}
									initial={animation3}
									layoutDependency={layoutDependency}
									layoutId={"X3om1BeHN"}
									onTap={onTapk75uvl}
									optimized={true}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-1eyg8rr"}
											data-styles-preset={"ByD69Lzay"}
											dir={"auto"}
										>
											<Link
												href={{
													hash: ":w_Xfqog0Q",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"X3om1BeHN"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"DmdlwUBKp"}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-161xcm"}
													data-styles-preset={"jbsOSsZpz"}
												>
													{"Testimonials"}
												</motion2.a>
											</Link>
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion2.div>
							<motion2.div
								className={"framer-1edh25x"}
								data-framer-name={"Row"}
								layoutDependency={layoutDependency}
								layoutId={"kZpewk3z2"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation6}
									className={"framer-1vusykn"}
									data-framer-appear-id={"1vusykn"}
									data-highlight={true}
									fonts={["Inter"]}
									initial={animation3}
									layoutDependency={layoutDependency}
									layoutId={"lfJobSbL0"}
									onTap={onTapk75uvl}
									optimized={true}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-1eyg8rr"}
											data-styles-preset={"ByD69Lzay"}
											dir={"auto"}
										>
											<Link
												href={{
													hash: ":cy05qZSsn",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"lfJobSbL0"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"DmdlwUBKp"}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-161xcm"}
													data-styles-preset={"jbsOSsZpz"}
												>
													{"Pricing"}
												</motion2.a>
											</Link>
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion2.div>
							<motion2.div
								className={"framer-w46xeh"}
								data-framer-name={"Row"}
								layoutDependency={layoutDependency}
								layoutId={"Hz5dUfUZG"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation7}
									className={"framer-qzyiw2"}
									data-framer-appear-id={"qzyiw2"}
									data-highlight={true}
									fonts={["Inter"]}
									initial={animation3}
									layoutDependency={layoutDependency}
									layoutId={"zErCtyg0X"}
									onTap={onTapk75uvl}
									optimized={true}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-1eyg8rr"}
											data-styles-preset={"ByD69Lzay"}
											dir={"auto"}
										>
											<Link
												href={{
													hash: ":EArIols72",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"zErCtyg0X"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"DmdlwUBKp"}
												smoothScroll={true}
											>
												<motion2.a
													className={"framer-styles-preset-161xcm"}
													data-styles-preset={"jbsOSsZpz"}
												>
													{"FAQ"}
												</motion2.a>
											</Link>
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-4u4t95"}
							data-framer-name={"Hamburger"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"mcQCi8vXb"}
							onTap={onTapk75uvl}
							transformTemplate={transformTemplate1}
						>
							{_jsx2(stdin_default, {
								animated: true,
								className: "framer-12mr3yc",
								layoutDependency,
								layoutId: "BnAonai7n",
								style: {
									"--1m973uw":
										"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(0, 0, 0))",
									"--js9iwy": 2,
								},
							})}
						</motion2.div>
					</MotionDivWithFXWithOptimizedAppearEffect>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aN4yM.framer-yt537p, .framer-aN4yM .framer-yt537p { display: block; }",
	".framer-aN4yM.framer-gfgffp { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 626px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 48px 0px 48px 0px; position: relative; width: 881px; }",
	".framer-aN4yM .framer-11oy1ps { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-aN4yM .framer-4ov5lt, .framer-aN4yM .framer-tlmpk2, .framer-aN4yM .framer-fmidhh, .framer-aN4yM .framer-1edh25x, .framer-aN4yM .framer-w46xeh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 4px 0px 4px 0px; position: relative; width: 100%; }",
	".framer-aN4yM .framer-cj8mrl, .framer-aN4yM .framer-a1ooox, .framer-aN4yM .framer-io8d4x, .framer-aN4yM .framer-1vusykn, .framer-aN4yM .framer-qzyiw2 { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-aN4yM .framer-4u4t95 { align-content: center; align-items: center; bottom: 64px; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 8px; position: absolute; width: min-content; z-index: 1; }",
	".framer-aN4yM .framer-12mr3yc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	...css3,
	...css,
];
var FramerDmdlwUBKp = withCSS2(Component2, css4, "framer-aN4yM");
var stdin_default2 = FramerDmdlwUBKp;
FramerDmdlwUBKp.displayName = "MobileMenu";
FramerDmdlwUBKp.defaultProps = {
	height: 626,
	width: 881,
};
addPropertyControls2(FramerDmdlwUBKp, {
	HYyn6lgsx: {
		title: "Close Overlay",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	FramerDmdlwUBKp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...XFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mobile-menu
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MobileMenuFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var mobile_menu_default = ComponentWithRoot;
export { mobile_menu_default as default };
