// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * openMobileNavigation?: Function // Open Mobile Navigation
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-2HMR454I.js";
import { stdin_default } from "./chunks/chunk-XMJR4DGB.js";
import "./chunks/chunk-K3KYO637.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-KXAZNTJD.js";
import { className, css, fonts } from "./chunks/chunk-FJRSPKHF.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-NJFOTUSO.js";
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:nav-bar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oD5PZSQhL3uUnvdWTeud/nsmEcy0UIK37dTyLFkPi/xIrDE0_gr.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/nW28P7k6zS9mddbwEi9t/eJZbsb780olVJmyBoSe8/Vsaktx242.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 16 0" fill="transparent" height="1px" id="YnobPTYMb" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(4 5)" width="16px"/><path d="M 0 0 L 16 0" fill="transparent" height="1px" id="Cb0Gao21R" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(4 12)" width="16px"/><path d="M 0 0 L 16 0" fill="transparent" height="1px" id="oPtuyu4df" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(4 19)" width="16px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className4,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("3467097230", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-grV1P", className4)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css4 = [
	`.framer-grV1P { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css4, "framer-grV1P");
Icon.displayName = "Menu";
var stdin_default3 = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/oD5PZSQhL3uUnvdWTeud/nsmEcy0UIK37dTyLFkPi/xIrDE0_gr.js
var SpeedometerFonts = getFonts(stdin_default2);
var ButtonFonts = getFonts(stdin_default);
var MenuFonts = getFonts(stdin_default3);
var cycleOrder = ["fnEiJvhOV", "k0VT3jbLt"];
var serializationHash = "framer-inmw1";
var variantClassNames = {
	fnEiJvhOV: "framer-v-1lw9r8",
	k0VT3jbLt: "framer-v-9th2j5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.12, 0.23, 0.4, 0.97],
	type: "tween",
};
var transition3 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var humanReadableVariantMap = {
	Desktop: "fnEiJvhOV",
	Mobile: "k0VT3jbLt",
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, openMobileNavigation, width, ...props }) => {
	return {
		...props,
		AQPx6yPta: openMobileNavigation ?? props.AQPx6yPta,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fnEiJvhOV",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		AQPx6yPta: AQPx6yPta2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fnEiJvhOV",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1fxp4fj = activeVariantCallback(async (...args) => {
		if (AQPx6yPta2) {
			const res = await AQPx6yPta2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "k0VT3jbLt") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "k0VT3jbLt") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							k0VT3jbLt: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1lw9r8",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fnEiJvhOV"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgb(34, 34, 34)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backdropFilter: "blur(10px)",
							backgroundColor: "rgba(18, 18, 18, 0.1)",
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						variants={{
							k0VT3jbLt: {
								backdropFilter: "blur(5px)",
								WebkitBackdropFilter: "blur(5px)",
							},
						}}
						{...addPropertyOverrides(
							{
								k0VT3jbLt: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-14auoc5"}
							layoutDependency={layoutDependency}
							layoutId={"h7a46a8UZ"}
						>
							<motion2.div
								className={"framer-1wxxgbh"}
								data-framer-name={"Links"}
								layoutDependency={layoutDependency}
								layoutId={"XJtjwX7on"}
							>
								<Link
									href={{
										webPageId: "augiA20Il",
									}}
									motionChild={true}
									nodeId={"pFE9WsetC"}
									scopeId={"xIrDE0_gr"}
								>
									<motion2.a
										className={"framer-17dtfti framer-1s72i4r"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"pFE9WsetC"}
									>
										<motion2.div
											className={"framer-75lixx"}
											data-border={true}
											layoutDependency={layoutDependency}
											layoutId={"aW46WisE5"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-393017ca-624a-4c0e-8abf-e25581b76ff1, rgba(0, 0, 0, 0.1))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-da609428-544a-4043-ad9a-562a44448ad4, rgb(255, 255, 255))",
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										>
											{_jsx2(stdin_default2, {
												animated: true,
												className: "framer-92sibv",
												layoutDependency,
												layoutId: "m3tRdYhiX",
												style: {
													"--1m6trwb": 0,
													"--21h8s6": "rgb(0, 0, 0)",
													"--pgex8v": 1.5,
												},
											})}
										</motion2.div>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1bhxwz6"}
											data-framer-name={"Spaces"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"acbofVJ_t"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-o5z0st"}
													data-styles-preset={"IsDMY7Ceo"}
													dir={"auto"}
												>
													{"Cadence"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
									</motion2.a>
								</Link>
								{isDisplayed() && (
									<motion2.div
										className={"framer-5goy0n"}
										data-framer-name={"Navigation Menu"}
										layoutDependency={layoutDependency}
										layoutId={"jAZPWZikr"}
									>
										<Transition value={transition3}>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1krk67a"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"dSgbneS9J"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
													>
														<Link
															href={{
																hash: ":kIdsWxA43",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"dSgbneS9J"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"xIrDE0_gr"}
															smoothScroll={true}
														>
															<motion2.a
																className={"framer-styles-preset-161xcm"}
																data-styles-preset={"jbsOSsZpz"}
															>
																{"Features"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</Transition>
										<Transition value={transition3}>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-15jhys5"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"E2UvvKZns"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-xsql1q"}
														data-styles-preset={"Awxi1CAQQ"}
														dir={"auto"}
													>
														<Link
															href={{
																hash: ":tuwYFvqCK",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"E2UvvKZns"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"xIrDE0_gr"}
															smoothScroll={true}
														>
															<motion2.a
																className={"framer-styles-preset-161xcm"}
																data-styles-preset={"jbsOSsZpz"}
															>
																{"Benefits"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</Transition>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-10gb2dk"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"DSvxMdDtJ"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-xsql1q"}
													data-styles-preset={"Awxi1CAQQ"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":w_Xfqog0Q",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"DSvxMdDtJ"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xIrDE0_gr"}
														smoothScroll={true}
													>
														<motion2.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Testimonials"}
														</motion2.a>
													</Link>
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-tw3szm"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"yX6v9mMci"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-xsql1q"}
													data-styles-preset={"Awxi1CAQQ"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":cy05qZSsn",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"yX6v9mMci"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xIrDE0_gr"}
														smoothScroll={true}
													>
														<motion2.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"Pricing"}
														</motion2.a>
													</Link>
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1y3oigl"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"kdCxfv0l7"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-xsql1q"}
													data-styles-preset={"Awxi1CAQQ"}
													dir={"auto"}
												>
													<Link
														href={{
															hash: ":EArIols72",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"kdCxfv0l7"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xIrDE0_gr"}
														smoothScroll={true}
													>
														<motion2.a
															className={"framer-styles-preset-161xcm"}
															data-styles-preset={"jbsOSsZpz"}
														>
															{"FAQ"}
														</motion2.a>
													</Link>
												</motion2.p>
											</React2.Fragment>
										</RichText>
									</motion2.div>
								)}
							</motion2.div>
							{isDisplayed() && (
								<ComponentViewportProvider
									height={48}
									y={(componentViewport?.y || 0) + 16 + 0 + 0}
								>
									<SmartComponentScopedContainer
										className={"framer-1rr8bv-container"}
										layoutDependency={layoutDependency}
										layoutId={"UcQlVnmLg-container"}
										nodeId={"UcQlVnmLg"}
										rendersWithMotion={true}
										scopeId={"xIrDE0_gr"}
									>
										{_jsx2(stdin_default, {
											H9fdquxmO: "Get started",
											height: "100%",
											id: "UcQlVnmLg",
											layoutId: "UcQlVnmLg",
											qa2d0SHwc: "https://framer.link/sbOJsNi",
											qZfHbmzQf: true,
											uFNDrhDvW: true,
											variant: matchVariant("n1t5mNkfc"),
											width: "100%",
											WqF2Pzc7v: "template-remixed-top-right",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed1() && (
								<motion2.div
									className={"framer-1robpw6"}
									data-framer-name={"Hamburger"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"QpUcK6mi5"}
									onTap={onTap1fxp4fj}
								>
									{_jsx2(stdin_default3, {
										animated: true,
										className: "framer-sgss3j",
										layoutDependency,
										layoutId: "fEXLHr8WG",
										style: {
											"--1m973uw": "rgb(255, 255, 255)",
											"--js9iwy": 2,
										},
									})}
								</motion2.div>
							)}
						</motion2.div>
					</motion2.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-inmw1.framer-1s72i4r, .framer-inmw1 .framer-1s72i4r { display: block; }",
	".framer-inmw1.framer-1lw9r8 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 24px 16px 24px; position: relative; width: 1184px; }",
	".framer-inmw1 .framer-14auoc5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1080px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-inmw1 .framer-1wxxgbh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-inmw1 .framer-17dtfti { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-inmw1 .framer-75lixx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); }",
	".framer-inmw1 .framer-92sibv { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-inmw1 .framer-1bhxwz6, .framer-inmw1 .framer-1krk67a, .framer-inmw1 .framer-15jhys5, .framer-inmw1 .framer-10gb2dk, .framer-inmw1 .framer-tw3szm, .framer-inmw1 .framer-1y3oigl { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-inmw1 .framer-5goy0n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-inmw1 .framer-1rr8bv-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-inmw1 .framer-1robpw6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px; position: relative; width: min-content; }",
	".framer-inmw1 .framer-sgss3j { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-inmw1.framer-v-9th2j5.framer-1lw9r8 { padding: 16px; width: 390px; }",
	".framer-inmw1.framer-v-9th2j5 .framer-1wxxgbh { flex-direction: column; }",
	...css3,
	...css2,
	...css,
	'.framer-inmw1[data-border="true"]::after, .framer-inmw1 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerxIrDE0_gr = withCSS2(Component2, css5, "framer-inmw1");
var stdin_default4 = FramerxIrDE0_gr;
FramerxIrDE0_gr.displayName = "NavBar";
FramerxIrDE0_gr.defaultProps = {
	height: 80,
	width: 1184,
};
addPropertyControls2(FramerxIrDE0_gr, {
	variant: {
		options: ["fnEiJvhOV", "k0VT3jbLt"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	AQPx6yPta: {
		title: "Open Mobile Navigation",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	FramerxIrDE0_gr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SpeedometerFonts,
		...ButtonFonts,
		...MenuFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerxIrDE0_gr.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:nav-bar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "k0VT3jbLt",
	xl: "fnEiJvhOV",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavBarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var nav_bar_default = ComponentWithRoot;
export { nav_bar_default as default };
