// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Off' | 'On' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:toggle
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/k9TwsP8rVSUwfId25lox/X824vpq2vxQxx33Ml9OX/uFRnc8IYR.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["EqF0iFMSN", "wyjdh50vS"];
var serializationHash = "framer-qBeF0";
var variantClassNames = {
	EqF0iFMSN: "framer-v-p6rvvs",
	wyjdh50vS: "framer-v-1j8lzit",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Off: "EqF0iFMSN",
	On: "wyjdh50vS",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		fgkjrWwJs: click ?? props.fgkjrWwJs,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "EqF0iFMSN",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		fgkjrWwJs: fgkjrWwJs2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "EqF0iFMSN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1efhlmf = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fgkjrWwJs2) {
			const res = await fgkjrWwJs2(...args);
			if (res === false) return false;
		}
		setVariant("wyjdh50vS");
	});
	const onTap1ee1yxe = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fgkjrWwJs2) {
			const res = await fgkjrWwJs2(...args);
			if (res === false) return false;
		}
		setVariant("EqF0iFMSN");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-p6rvvs",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Off"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"EqF0iFMSN"}
						onTap={onTap1efhlmf}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 48,
							borderBottomRightRadius: 48,
							borderTopLeftRadius: 48,
							borderTopRightRadius: 48,
							...style,
						}}
						variants={{
							wyjdh50vS: {
								backgroundColor: "rgba(255, 255, 255, 0.12)",
							},
						}}
						{...addPropertyOverrides(
							{
								wyjdh50vS: {
									"data-framer-name": "On",
									onTap: onTap1ee1yxe,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1oebm67"}
							layoutDependency={layoutDependency}
							layoutId={"M_Ixrmy7H"}
							style={{
								backgroundColor:
									"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
								borderBottomLeftRadius: "50%",
								borderBottomRightRadius: "50%",
								borderTopLeftRadius: "50%",
								borderTopRightRadius: "50%",
							}}
							transformTemplate={transformTemplate1}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qBeF0.framer-glbf66, .framer-qBeF0 .framer-glbf66 { display: block; }",
	".framer-qBeF0.framer-p6rvvs { cursor: pointer; height: 24px; overflow: hidden; position: relative; width: 48px; will-change: var(--framer-will-change-override, transform); }",
	".framer-qBeF0 .framer-1oebm67 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); left: 4px; overflow: hidden; position: absolute; top: 50%; width: 16px; will-change: var(--framer-will-change-override, transform); }",
	".framer-qBeF0.framer-v-1j8lzit .framer-1oebm67 { left: unset; right: 4px; }",
	'.framer-qBeF0[data-border="true"]::after, .framer-qBeF0 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FrameruFRnc8IYR = withCSS(Component, css, "framer-qBeF0");
var stdin_default = FrameruFRnc8IYR;
FrameruFRnc8IYR.displayName = "Toggle";
FrameruFRnc8IYR.defaultProps = {
	height: 24,
	width: 48,
};
addPropertyControls(FrameruFRnc8IYR, {
	variant: {
		options: ["EqF0iFMSN", "wyjdh50vS"],
		optionTitles: ["Off", "On"],
		title: "Variant",
		type: ControlType.Enum,
	},
	fgkjrWwJs: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FrameruFRnc8IYR,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:toggle
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "EqF0iFMSN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ToggleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var toggle_default = ComponentWithRoot;
export { toggle_default as default };
