// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
}} Props

 */
import { routes } from "./chunks/chunk-NLZWQNGZ.js";

// virtual:use-template-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oWaGBwx7PJnNCeSJcV7g/7i2D6g2x2NZAiERuJbsx/dWir_Xsx6.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/JAHMTokngeA9GGzisyGP/XLcGrOA17MFCAwuXi5mB/oK82mNmE_.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 0 4.5 L 7.5 4.5 L 7.5 12 L 12 12 L 12 0 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="12px" id="cfNFsTWLl" transform="translate(8.25 3.75)" width="12px"/><path d="M 7.5 12 L 12 12 L 12 0 L 0 0 L 0 4.5" fill="transparent" height="12px" id="ODJ_TeZYo" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 3.75)" width="12px"/><path d="M 0 12 L 0 0 L 12 0 L 12 12 Z" fill="transparent" height="12px" id="Ea3BNSkj5" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3.75 8.25)" width="12px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("743177299", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-vKAxf", className)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css = [
	`.framer-vKAxf { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-vKAxf");
Icon.displayName = "Copy";
var stdin_default = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/oWaGBwx7PJnNCeSJcV7g/7i2D6g2x2NZAiERuJbsx/dWir_Xsx6.js
var CopyFonts = getFonts(stdin_default);
var enabledGestures = {
	FUYng_xQZ: {
		hover: true,
	},
};
var serializationHash = "framer-KM5c2";
var variantClassNames = {
	FUYng_xQZ: "framer-v-16ns41d",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, link, width, ...props }) => {
	return {
		...props,
		tuOGV3ijT: link ?? props.tuOGV3ijT,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		tuOGV3ijT: tuOGV3ijT2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "FUYng_xQZ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						clickTrackingId={"template-duplicated"}
						href={tuOGV3ijT2}
						motionChild={true}
						nodeId={"FUYng_xQZ"}
						openInNewTab={true}
						scopeId={"dWir_Xsx6"}
						smoothScroll={false}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-16ns41d", className, classNames)} framer-1czrdu0`}
							data-border={true}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"FUYng_xQZ"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(0, 0, 0, 0.08)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
								boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.12)",
								...style,
							}}
							variants={{
								"FUYng_xQZ-hover": {
									backgroundColor: "rgb(237, 237, 237)",
								},
							}}
							{...addPropertyOverrides(
								{
									"FUYng_xQZ-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{_jsx2(stdin_default, {
								animated: true,
								className: "framer-oovc52",
								layoutDependency,
								layoutId: "PBy0qaxTN",
								style: {
									"--1m6trwb": 0,
									"--21h8s6": "rgb(0, 0, 0)",
									"--pgex8v": 2,
								},
							})}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-cmvddt"}
								fonts={["GF;DM Sans-500"]}
								layoutDependency={layoutDependency}
								layoutId={"pJWxID51J"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-34d58044-5fb0-4480-9bc8-4e91d499d8e6, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7RE0gU2Fucy01MDA=",
											"--framer-font-family":
												'"DM Sans", "DM Sans Placeholder", sans-serif',
											"--framer-font-size": "14px",
											"--framer-font-weight": "500",
											"--framer-line-height": "1.3em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-34d58044-5fb0-4480-9bc8-4e91d499d8e6, rgb(0, 0, 0)))",
										}}
									>
										{"Use template"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KM5c2.framer-1czrdu0, .framer-KM5c2 .framer-1czrdu0 { display: block; }",
	".framer-KM5c2.framer-16ns41d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 36px; justify-content: center; overflow: hidden; padding: 12px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-KM5c2 .framer-oovc52 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 16px; }",
	".framer-KM5c2 .framer-cmvddt { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	'.framer-KM5c2[data-border="true"]::after, .framer-KM5c2 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerdWir_Xsx6 = withCSS2(Component2, css2, "framer-KM5c2");
var stdin_default2 = FramerdWir_Xsx6;
FramerdWir_Xsx6.displayName = "UseTemplateButton";
FramerdWir_Xsx6.defaultProps = {
	height: 36,
	width: 136,
};
addPropertyControls2(FramerdWir_Xsx6, {
	tuOGV3ijT: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts(
	FramerdWir_Xsx6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "DM Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Sans",
					url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
					weight: "500",
				},
			],
		},
		...CopyFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:use-template-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders UseTemplateButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var use_template_button_default = ComponentWithRoot;
export { use_template_button_default as default };
