// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b3697e5bb129d3c "Cadence (copy)", do not edit manually */
"use client";

import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-2HMR454I.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-TYSSTXWB.js";
import { className, css, fonts } from "../chunks/chunk-NTQNEBCY.js";
import { routes } from "../chunks/chunk-NLZWQNGZ.js";

// virtual:cards/testimonial
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/g1uqNPeJeBauxIidxent/5Sv6McGPyOjob9zlrhWm/tYuQBCh0g.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/yZenMgzAnb2d9zq3q2H6/u0HFQMZGuhmrdq5jqLCu/TuMmphZKc.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-mo3mb";
var variantClassNames = {
	QSCyPsfo4: "framer-v-1gq8fwc",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ avatar, height, id, width, ...props }) => {
	return {
		...props,
		cpsLDpTtE: avatar ?? props.cpsLDpTtE,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		cpsLDpTtE,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "QSCyPsfo4",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							sizes: componentViewport?.width || "100vw",
							...toResponsiveImage(cpsLDpTtE),
						}}
						className={cx(
							scopingClassNames,
							"framer-1gq8fwc",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"QSCyPsfo4"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(255, 255, 255, 0.1)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 999,
							borderBottomRightRadius: 999,
							borderTopLeftRadius: 999,
							borderTopRightRadius: 999,
							...style,
						}}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mo3mb.framer-obhczo, .framer-mo3mb .framer-obhczo { display: block; }",
	".framer-mo3mb.framer-1gq8fwc { height: 40px; overflow: hidden; position: relative; width: 40px; will-change: var(--framer-will-change-override, transform); }",
	'.framer-mo3mb[data-border="true"]::after, .framer-mo3mb [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerTuMmphZKc = withCSS(Component, css4, "framer-mo3mb");
var stdin_default = FramerTuMmphZKc;
FramerTuMmphZKc.displayName = "Elements/Avatar";
FramerTuMmphZKc.defaultProps = {
	height: 40,
	width: 40,
};
addPropertyControls(FramerTuMmphZKc, {
	cpsLDpTtE: {
		title: "Avatar",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerTuMmphZKc,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/g1uqNPeJeBauxIidxent/5Sv6McGPyOjob9zlrhWm/tYuQBCh0g.js
var ElementsAvatarFonts = getFonts(stdin_default);
var serializationHash2 = "framer-E8Vdo";
var variantClassNames2 = {
	XlUPXL0sp: "framer-v-qjxmf5",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({
	avatar,
	client,
	height,
	id,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		c5PhFvhFc: avatar ?? props.c5PhFvhFc,
		ECqJZ1hHM: title ?? props.ECqJZ1hHM ?? "Startup Founder",
		oRy6t91PU: client ?? props.oRy6t91PU ?? "Sara T.",
		VePkjXSEB:
			text ??
			props.VePkjXSEB ??
			'"Breeze completely changed how I work. I get more done in less time without feeling overwhelmed."',
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		VePkjXSEB: VePkjXSEB2,
		c5PhFvhFc: c5PhFvhFc2,
		oRy6t91PU: oRy6t91PU2,
		ECqJZ1hHM: ECqJZ1hHM2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "XlUPXL0sp",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-qjxmf5",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"XlUPXL0sp"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-df227308-60be-4193-a99e-717d73a86df8, rgba(255, 255, 255, 0.12))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-37b21b3d-3e44-4bf1-bf68-f20e67e05dae, rgb(18, 18, 18))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-8kmqev"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"mTkwiYT_7"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={VePkjXSEB2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-xsql1q"}
									data-styles-preset={"Awxi1CAQQ"}
									dir={"auto"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-fa4dcb27-7179-41c9-bbdc-0fe7fe502e97, rgb(255, 255, 255)))",
									}}
								>
									{
										'"Breeze completely changed how I work. I get more done in less time without feeling overwhelmed."'
									}
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<motion2.div
							className={"framer-ufctim"}
							data-framer-name={"Client"}
							layoutDependency={layoutDependency}
							layoutId={"L2Wese7dN"}
						>
							<ComponentViewportProvider
								height={36}
								width={"36px"}
								y={
									(componentViewport?.y || 0) +
									24 +
									(0 +
										104 +
										(((componentViewport?.height || 200) - 48 - 267) / 1) * 1) +
									63.5
								}
							>
								<SmartComponentScopedContainer
									className={"framer-x7358w-container"}
									layoutDependency={layoutDependency}
									layoutId={"uKguabsO2-container"}
									nodeId={"uKguabsO2"}
									rendersWithMotion={true}
									scopeId={"tYuQBCh0g"}
								>
									{_jsx2(stdin_default, {
										cpsLDpTtE: toResponsiveImage2(c5PhFvhFc2),
										height: "100%",
										id: "uKguabsO2",
										layoutId: "uKguabsO2",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion2.div
								className={"framer-f4oezu"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"aeZwoBlN_"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7dktt1"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Y3kjatpAf"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={oRy6t91PU2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-z5yjcz"}
											data-styles-preset={"I1dFaNZDG"}
											dir={"auto"}
										>
											{"Sara T."}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-15v6jwl"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"GmFRuuRSU"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={ECqJZ1hHM2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-2dwwia"}
											data-styles-preset={"KFJNmiObh"}
											dir={"auto"}
										>
											{"Startup Founder"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-E8Vdo.framer-f4uy73, .framer-E8Vdo .framer-f4uy73 { display: block; }",
	".framer-E8Vdo.framer-qjxmf5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 200px; justify-content: space-between; overflow: hidden; padding: 24px; position: relative; width: 351px; will-change: var(--framer-will-change-override, transform); }",
	".framer-E8Vdo .framer-8kmqev { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-E8Vdo .framer-ufctim { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-E8Vdo .framer-x7358w-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 36px); position: relative; width: 36px; }",
	".framer-E8Vdo .framer-f4oezu { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-E8Vdo .framer-7dktt1, .framer-E8Vdo .framer-15v6jwl { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
	...css3,
	'.framer-E8Vdo[data-border="true"]::after, .framer-E8Vdo [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramertYuQBCh0g = withCSS2(Component2, css5, "framer-E8Vdo");
var stdin_default2 = FramertYuQBCh0g;
FramertYuQBCh0g.displayName = "Cards/Testimonial";
FramertYuQBCh0g.defaultProps = {
	height: 200,
	width: 351,
};
addPropertyControls2(FramertYuQBCh0g, {
	VePkjXSEB: {
		defaultValue:
			'"Breeze completely changed how I work. I get more done in less time without feeling overwhelmed."',
		displayTextArea: true,
		title: "Text",
		type: ControlType2.String,
	},
	onVePkjXSEBChange: {
		changes: "VePkjXSEB",
		type: ControlType2.ChangeHandler,
	},
	c5PhFvhFc: {
		title: "Avatar",
		type: ControlType2.ResponsiveImage,
	},
	oRy6t91PU: {
		defaultValue: "Sara T.",
		displayTextArea: false,
		title: "Client",
		type: ControlType2.String,
	},
	onoRy6t91PUChange: {
		changes: "oRy6t91PU",
		type: ControlType2.ChangeHandler,
	},
	ECqJZ1hHM: {
		defaultValue: "Startup Founder",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	onECqJZ1hHMChange: {
		changes: "ECqJZ1hHM",
		type: ControlType2.ChangeHandler,
	},
});
addFonts2(
	FramertYuQBCh0g,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsAvatarFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramertYuQBCh0g.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:cards/testimonial
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b3697e5bb129d3c71c05c59d73d6e0c3c1758fd6dac75acd6c14ffd690b0d75"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var testimonial_default = ComponentWithRoot;
export { testimonial_default as default };
